### ISSUE TITLE
[FEATURE_REQUEST] Goodreads backend support

### ISSUE THREAD

**Issue by mizzunet** [mateusz-bak/openreads-android#110]
**Is your feature request related to a problem? Please describe.**
OpenLibrary database missing plenty of books

**Describe the solution you'd like**
* Use Goodreads as a backend or 
* make it available as an option and let user can choose it.

**Describe alternatives you've considered**
I wrote an unofficial API thingy for Goodreads. It's not perfect, but it works.
https://gruapi.herokuapp.com/

Limitations:
* It'd take 2-3 seconds to get the output

**Additional context**
Feel free to make any suggestions. Though I'm still rookie at Go, I'll see what I can do.

**Comment by mateusz-bak** [comment]
Hey @mizzunet I'm thinking really hard about adding different sources for book searches. 

Regarding Goodreads database I'm not convinced that it will suit Openreads. I'm going through their [terms & conditions](https://www.goodreads.com/api/terms) and see some obstacles like:
- `Not use the API to harvest or index Goodreads data without our explicit written consent.` - I don't think they will allow this for a competitor app.
- `Not modify or change Goodreads data, including reviews, in any way. Reviews may be truncated for display purposes, but must link to the full review on Goodreads.` - When we add a book we can change it's details,

And they don't currently issue new API keys? `As of December 8th 2020, Goodreads no longer issues new developer keys for our public developer API and plans to retire the current version of these tools. ` 

Would your API on heroku resolve any of this problems and how reliable / stable is it?

Cheers!

**Comment by mateusz-bak** [comment]
@mizzunet sorry for the delay. I thought again and I don't see that could work with Openreads. Thanks for your inputs
