### ISSUE TITLE
[BUG] Search cannot find ebooks

### ISSUE THREAD

**Issue by matthias4217** [mateusz-bak/openreads-android#116]
**Describe the bug**

When looking for an ebook from OpenLibrary, such as [Black Library Celebration 2022](https://openlibrary.org/works/OL27774951W/Black_Library_Celebration_2022), I cannot find it using the Openreads search.

**To Reproduce**

Unfortunately, I haven't found much ebooks in OpenLibrary. The only ones I have found are the ones I have added. I'd like to have some more examples, because maybe I've made a mistake when adding those ?

**Expected behavior**

Maybe this is a design choice, but since I read some ebooks, I'd like to add them to the app from OpenLibrary and not only manually. I've looked a bit at the code, but my poor level in Kotlin and Android hasn't helped me find where this issue could come from.

**Additional info(please complete the following information):**
 - Manufacturer and model: LG G5
 - Android version: 11
 - App version: 1.14.2
 - App source (F-Droid, Google Play, Github): F-Droid

**Additional context**

I really love Openreads ! Thank you very much for your work !

**Comment by mateusz-bak** [comment]
Hey @matthias4217 thank you for submitting this issue! I will check why there's a problem with ebooks. Cheers!

**Comment by mateusz-bak** [comment]
Ok found the issue: search for this books returns a record with two ISBN numbers that are missing from Open Library. App will look up the book also by Open Library ID. 
Currently it would search by OLID only when ISBN was missing.

Thanks for the contribution, fix will be released in v1.16.0
