### ISSUE TITLE
[FEATURE_REQUEST] Progress bar per book for the books "In progress"

### ISSUE THREAD

**Issue by Khyta** [mateusz-bak/openreads-android#122]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i cannot see the progress of a book being currently read on the app in the "In progress" tab.

**Describe the solution you'd like**
I would like to have a progress bar ranging from 0-100% to see how far you've read. I would also for that to work add a field which says "Progress:" and in which you could eithet input the page number or the percentage itself.

**Describe alternatives you've considered**
Make the cover uncover itself when progressing through the book. Or just don't have any progress indicator  for each book in the "In progress" section.

**Additional context**
Thanks for the amazing app btw! Really enjoy it :)

**Comment by apobrt** [comment]
A similar proposal already exists: #61 . We close this, follow the other one for updates
