### ISSUE TITLE
[BUG] App crashes when adding book

### ISSUE THREAD

**Issue by GeorgelPreput** [mateusz-bak/openreads-android#124]
App crashes on Samsung S21 when trying to add book as follows:

- open app
- tap + button
- select Search in OpenLibrary
- paste in 9781847921260
- select any result
- hide the keyboard

**Comment by mateusz-bak** [comment]
Thanks for the inputs, will check what's causing the problem.

**Comment by mateusz-bak** [comment]
Found the issue and improved handling of books with `null` as cover ID. Will be fixed in v1.16.0, thanks for the help!
