### ISSUE TITLE
[FEATURE_REQUEST] Sort by authors last name

### ISSUE THREAD

**Issue by unchartedpopsicle** [mateusz-bak/openreads-android#125]
**Is your feature request related to a problem? Please describe.**
When sorting by author the app currently goes by first name.

**Describe the solution you'd like**
Please sort it by last name instead.

**Comment by apobrt** [comment]
I spent some time these weeks thinking about a clever solution for this, but I didn't find one.

The first big problem is that we don't have the information about what is the first name, and what is the last name. In the OpenLibrary db, the data is stored as "author" (as it is in this app), so it uses only one field.
We could split the field into two, using the space as a separator, but quickly I realized it's not a good idea: if an author has tow or more names? Or surnames? 
Or if the author uses an art name, which is not a first name nor a last name?
If it is only a single word, how should we handle it? It's the first name or the last name? Both?
If the author is more than one?

Same if the book is written by a magazine or by any organization which is not a real person.

I also think to not consider all of this, and implement anyway two fields ("First name" and "Last name") filled automatically by the splitting of the author data: if something is wrong, the user can always manually edit it. But I really don't like this approach.

So, in the end, I thought that the best solution is the one we have already :smile:

**Comment by mateusz-bak** [comment]
Yeah it's a lot of issues when thinking about this. The best would be if Open Library would have the data already separated by first and last name like Goodreads (I've see that it is like this in the export CSV).

In the current way the decision is left to the user - however they input the authors - that is how it will be sorted.

**Comment by apobrt** [comment]
I'm curious to know how Goodreads handle some of the cases I mentioned above, I will check at some point.

For us, I fear that we should close this issue until OpenLibrary passes us the two separate data. 
We can re-open this if something changes in the future
