### ISSUE TITLE
[FEATURE_REQUEST] Add a camera chooser dialog

### ISSUE THREAD

**Issue by Turbolqk** [mateusz-bak/openreads-android#133]
When taking a photo of a book cover,  adding a camera dialog (choose your camera app) or respecting the system default choice should be the norm. 
Right now if you use a different camera app (OpenCamera) and disable the stock one (Camera2) the app crashes because it cant find the stock one.

**Comment by bsvka** [comment]
Can't reproduce. I get asked which camera should fulfill the intent.

**Comment by mateusz-bak** [comment]
As taking cover pictures was removed in v2.0 this issue is no longer relevant. If anyone would like to see the option to photograph covers please create another feature request.
