### ISSUE TITLE
[BUG] Can't properly add OL27720165W

### ISSUE THREAD

**Issue by bsvka** [mateusz-bak/openreads-android#134]
**Describe the bug**
When searching for "M.D. trinkt" the book is found correctly. When I click it, not all data available from OL is copied and the OL ID is botched. Title, publish year and cover work, No. of pages is lost and the ID is missing the last 3 characters. See screenshot below.

**To Reproduce**
1. Search "M.D. trink"
2. Add book

**Expected behavior**
Correctly fetch data, don't botch ID.

**Screenshots**
![Screenshot_20220718-205916](https://user-images.githubusercontent.com/109389712/179598171-c695b8c9-6731-4ee3-82f8-750c9b799dd6.jpg)

**Additional info(please complete the following information):**
 - Manufacturer and model: -
 - Android version: 10
 - App version: 1.16.0
 - App source (F-Droid, Google Play, Github): F-Droid

**Additional context**
Book doesn't have an ISBN or author associated with it.

**Comment by notjedi** [comment]
[works/OL277201](https://openlibrary.org/works/OL277201) does not exist. nor do i get any [results](https://openlibrary.org/search?q=M.D.+trink&mode=everything).

**Comment by notjedi** [comment]
this is an [openlibrary](openlibrary.org) issue. the [webpage](https://openlibrary.org/works/OL27720165W/M.D._trinkt_Abends_gerne_ein_Bier) corresponding to the book does not have any ISBN in it.

**Comment by mateusz-bak** [comment]
@bsvka @notjedi Fixed, will be released in v1.17.0
