### ISSUE TITLE
[FEATURE_REQUEST] automated & shared cloud sync

### ISSUE THREAD

**Issue by abaumfalk** [mateusz-bak/openreads-android#136]
**Is your feature request related to a problem? Please describe.**
We have a library which is shared among the family, so I would like to share the catalog, too.

**Describe the solution you'd like**
I would like to use private shared cloud space to share the catalog in a way that it is automatically synced with all participants. To avoid conflicts I could live with some simple restrictions: exclusive editing and no offline editing.

**Describe alternatives you've considered**
Manual sync using save-to-cloud/file and restore seems risky and inconvenient, because when editing it would be crucial to manually follow a restore-edit-backup cycle. This is way too complicated for some family members.

**Comment by mateusz-bak** [comment]
@abaumfalk cloud functions would require user registration and funding to support the servers. Its not possible at this moment
