### ISSUE TITLE
[BUG] App crashes when changing a book from "Finished" to "In Progress" or "For Later"

### ISSUE THREAD

**Issue by biicwlim** [mateusz-bak/openreads-android#138]
**Describe the bug**
If a book is imported and accidentally (or intentionally) listed as finished, then moved to "in progress" or "for later", the app crashes.  It can then be reopened with the change complete.

**Expected behavior**
Such a data change should occur without the app to crashing.

**Additional info(please complete the following information):**
Cricket Icon 3
Android 11
Openreads 1.16.0
F-Droid

**Comment by mateusz-bak** [comment]
@biicwlim please reopen if issue still occurs after 2.0.0 update.
