### ISSUE TITLE
[FEATURE_REQUEST] Improved Tags or a Location column

### ISSUE THREAD

**Issue by biicwlim** [mateusz-bak/openreads-android#139]
**Is your feature request related to a problem? Please describe.**
My use case is keeping track of the books I own, where they go, and what I have loaned out.
Right now I use tags to split them by genre / section, if it is an eBook, and if I am borrowing one or have it loaned out.  Books that I am using or have at home instead of on the office shelf get put in "in progress".

**Describe the solution you'd like**
If that's not a supported use case and you're not interested, no problem.  But a few possible things that seem to me would be really helpful:

1) When editing a book, have a drop-down menu or something to select from a list of the tags currently used, in addition to typing in a new tag.

2) Make an easier UX to see and select from a large number of tags in the sort books menu (perhaps having the tags roll over onto multiple rows instead of having to scroll through them longways?)

3) Add an extra "location" category as a new optional column for each record.  For those tracking their physical books, as well as reading history, this would allow them to sort them by shelves, where they got the book, etc.

*******
Thanks for making a great and super useful app!  I was very glad to be able to move from the non-open source alternative I previously used.

**Comment by teslahitchhiker42** [comment]
Would making it so users could add arbitrary lists solve this issue? I've wanted to make lists apart from the 4 that already exist (Finished, In Progress, For later, and Not finished). I would use it for a "To read again" list and a "in progress but need to start over reading" list specifically.

**Comment by biicwlim** [comment]
Yes, that would make the app much easier for my case!  I would make a "Borrowed" and a "Home" list.
I know I'm kind using the app "off-label" for a different use case, but you've written a great app that seems to be filling a unique niche in the open source world.

**Comment by teslahitchhiker42** [comment]
Oops, lol, I realize my comment made it sound like I'm a developer. I only meant that I wish the app allowed for creating more lists, not that I wanted to add the feature myself. But it sounds like a feature allowing the creation of arbitrary lists would solve the issue both you and I are having.

**Comment by mateusz-bak** [comment]
Hi @biicwlim number 1 is gonna be implemented in 2.1 release. 
The 2 and 3 I think would clutter the app too much, really trying to keep the app as simple as possible.

Hope you found your way with the tags!
