### ISSUE TITLE
[FEATURE_REQUEST] Sort by first published date

### ISSUE THREAD

**Issue by Johnny5sword** [mateusz-bak/openreads-android#145]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option of sorting the books in your library in chronological order or latest to earliest. 

**Describe the solution you'd like**
Add another option in the sort books option for ordering the books by first published date

**Describe alternatives you've considered**
Another Android FOSS app, [Badreads](https://github.com/fenimore/badreads), has this feature but it would be nice to have it implemented in Openreads

**Comment by apobrt** [comment]
Related to #125

**Comment by mateusz-bak** [comment]
I'll add a new sort option - by publication year
