### ISSUE TITLE
Error when sorting by date finished

### ISSUE THREAD

**Issue by miguelmaiquez** [mateusz-bak/openreads-android#147]
Books with certain finished dates aren't sorted right.

When a book is added with 1982 as the finished date, it is listed before the 2000s ones, even if the list is sorted in descendent order (or after, if it's sorted in ascending order). Same thing wth books with other 1980s dates, etc.

![or](https://user-images.githubusercontent.com/5161774/189511704-9fa9a947-6dc3-4fca-a8e4-eb6ce9cb9d1b.png)

- Android version: Android 8.1.0
- App version: 1.16.0
- App source: F-Droid

**Comment by mateusz-bak** [comment]
@miguelmaiquez please reopen if issue still occurs after 2.0.0 update.
