### ISSUE TITLE
A more flexible way to add the date finished

### ISSUE THREAD

**Issue by miguelmaiquez** [mateusz-bak/openreads-android#148]
Right now, adding an old date as the date finished (1980, for example) means pressing the calendar arrows multiple times until reaching the desired date (month by month, year by year).

Also, the current calendar system only allows to add exact dates, when we often remember the year we finished reading a book, but not the day and the month.

Both problems could be solved, if possible, with an option to manually filling a date field, also allowing the month and/or day to be left blank.

![date](https://user-images.githubusercontent.com/5161774/189512102-3fbd613c-ed4c-42c3-bead-c541d64428e4.png)

Another option:

![date 2](https://user-images.githubusercontent.com/5161774/189512844-cdb81384-cd1c-4fa0-959c-3d9b63f696f1.png)

**Comment by mateusz-bak** [comment]
@miguelmaiquez date adding should be faster now, but the day and month will remaij required for the time being
