### ISSUE TITLE
[FEATURE_REQUEST] Add "Remember Last Position In The List" option in the Settings

### ISSUE THREAD

**Issue by brucetheelephant** [mateusz-bak/openreads-android#151]
**Is your feature request related to a problem? Please describe.**
So after you View or Edit a book and press Back, the Tab View is "refreshed" and you are shown the top of the tab, the top of your list. When you want to View or Edit multiple books which are lower in the list, you have to scroll down, perform the operation, press back, then scroll down again (because the Tab View saw "refreshed"), perform the operation, press back, then scroll down again etc etc etc. When you have tens or hundreds of books in the list then this gets very very annoying.

**Describe the solution you'd like**
I want you to add a "Remember Last Position In The List" option in the Settings.

**Describe alternatives you've considered**
Alternatively you can just add this feature as standard behaviour for when you press Back after you View or Edit an entry.

**Comment by mateusz-bak** [comment]
@brucetheelephant should work like this after 2.0.0 update
