### ISSUE TITLE
[FEATURE_REQUEST] Select covers from Open Library for imported books

### ISSUE THREAD

**Issue by MichalSvatos** [mateusz-bak/openreads-android#152]
**Is your feature request related to a problem? Please describe.**
I've just imported books from Goodreads CSV and all the books are without cover.

**Describe the solution you'd like**
Possible solutions I can think of.
- Option to "merge"/"link" local book to Open Library to fill missing information.
- Add option to the popup menu - [Take photo of your cover], [Upload cover from storage], [**Search Open Library for cover**]
- Choose a cover based on Open Library ID that user provides. Not super user friendly, but managable and better than hassling with many files.

**Describe alternatives you've considered**
Alternative _solutions_ (more like tedious workaround) is download covers from the internet and manually add them to every single book. Unless user have 3 books, it's not viable.

Thank you for considering this request.

**Comment by mateusz-bak** [comment]
I added a new screen in the settings to download missing covers from Open Library for books that have ISBN set.
