### ISSUE TITLE
Keep track of who you've lent your books to (and who lent you some) [FEATURE_REQUEST] 

### ISSUE THREAD

**Issue by sonalder-darlene** [mateusz-bak/openreads-android#153]
As physical books are really nice when you want to lent them to your friends or familiy they can often be lost.
If OpenReads could keep tracks of my reading and my lending books it would be amazing.
Also having the feature to note who lent you this book so you don't forget to give it back when you're done reading it.

When you had a book you should have a checkbox that indicate that this book isn't yours.
Then if it's checked you could add a contact to it. When the book is marked as read on the app show a message like "Don't forget to give the book back to [contact here]"
Adding a new categorie of lent books. In this one you can add books and pair them with the contact you lent the book to.
So now in one tab you can easily see who has which book and never loose them again ^^

Being able to manually type a name should be an option as some people wont like giving contact access to a book app

I've lost some books --'

**Comment by mateusz-bak** [comment]
Hi @sonalder-darlene we can use tags to add "borrowed" label or something for the books. Think this should be enough
