### ISSUE TITLE
[FEATURE_REQUEST]  UI Improvements etc

### ISSUE THREAD

**Issue by skeptronus** [mateusz-bak/openreads-android#154]
1. "Add a new book":
- The default status is "finished". I think it is more reasonable to use "In progress", as when someone's adding a new book, it is more likely that they are currently reading it. Also in that case the current date should be the start date, not finish date.
- The save button is at the bottom of the screen, which is not very convenient. A button at the top or a floating button would be better.
2. "In Progress" tab should come before the "Finished" tab in the main activity. Or an option should be provided to arrange the tabs.
3. Long-click options should be provided for editing entries. 
4. If the save button is clicked before it finishes fetching the cover from web, the entry gets saved without a cover image . the missing cover image should instead be fetched in the background and added.

**Comment by mateusz-bak** [comment]
I like the ideas here.

First the book status of new book depends on from what tab you add it like @PassionateG1t said. 

I agree to the point that when adding a new book from in progress tab should have today's date prefilled - will correct that.

And also agree on re-arranging the tabs.

All this will be implemented in the v2 refactor I'm currently working on.

**Comment by mateusz-bak** [comment]
@skeptronus 
There has been 2.0.0 release
1. You can set in progress tab as the first one in settings. The status of a new book is not selected by default, if you click in progress a today's date will be set as start date.
Save button is now on top.
2. Option provided
3. Not implementing for now
4. Now there's a download indicator so you know when to save
