### ISSUE TITLE
[BUG] Crash when creating cloud backup

### ISSUE THREAD

**Issue by DSiekmeier** [mateusz-bak/openreads-android#155]
**Describe the bug**
The app crashes without any message when selecting the menu point "Create oud backup" (Cloud-Backup erstellen). 

**To Reproduce**
Tap on the menu point under settings.

**Expected behavior**
Some appropriate dialog should appear, I guess.

**Additional info(please complete the following information):**
 - Manufacturer and model: Huawei P30 lite
 - Android version: EMUI 12
 - App version: 1.16.0
 - App source: F-Droid

**Comment by mateusz-bak** [comment]
Hi, so sorry to hear that. Are you able to create a local backup?

I'm working currently on the app refactor and backup should cause less issues.

**Comment by DSiekmeier** [comment]
Actually also creating a local backup does not work. There appears a toast, saying the file was saved successfully, but the folder on the local storage is empty.

**Comment by mateusz-bak** [comment]
@DSiekmeier please reopen if issue still occurs after 2.0.0 update.
