### ISSUE TITLE
[FEATURE_REQUEST] Smoother UI for adding a book from Open Library

### ISSUE THREAD

**Issue by magnus-ISU** [mateusz-bak/openreads-android#157]
**Is your feature request related to a problem? Please describe.**
 ~~I'm always frustrated when adding a book from OL because often the same book is listed several times in different languages and it is harder than it should be to pick out the right one.~~

Also, after finding the right book, I don't typically manually edit the fields. The way it currently works though, I have to hide the keyboard and scroll down before being able to add the book.

**Describe the solution you'd like**
~~Add a way to select a preferred language on open reads, and give it significant weight in how the results are ordered. Or at least, make the top result always in that language if possible.~~

Also, after clicking the book, it should immediately be added. A long press should bring up the detailed manual edit view.

**Describe alternatives you've considered**
~~No alternatives for the language thing.~~

A long press instead skips the manual edit review, to avoid changing user expectations (though I think this is a worse overall experience, as it isn't discoverable).

The 'Save' button is more accessibly placed so it is always on screen in the manual edit page.

**Comment by magnus-ISU** [comment]
You can filter by language, and its preserved across app restarts. I'm dumb.

**Comment by mateusz-bak** [comment]
@magnus-ISU closing this as book search functionality has been heavily refactored in 2.0.0 release, hope it works better now!
