### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by brucetheelephant** [mateusz-bak/openreads-android#164]
**Describe the bug**
New books don't appear / don't show in the list after adding them.
They are there because if I search for them using the SEARCH function I can find them, I can click on the title and I can view the book information but if I just scroll down the list the book does not appear / does not show there.

**To Reproduce**
Steps to reproduce the behavior: Add a new book and see if it appears on the list.

**Expected behavior**
..

**Screenshots**
N/A

**Additional info(please complete the following information):**
 - Manufacturer and model: Xiaomi Mi A2 Lite
 - Android version: 10
 - App version: 1.17.1-rc1.29
 - App source (F-Droid, Google Play, Github): F-Droid

**Additional context**
..

**Comment by mateusz-bak** [comment]
Hi @brucetheelephant maybe to book is sorted out by your filters?
