### ISSUE TITLE
[FEATURE_REQUEST] associate a file with a book, and open with an ebook reader from openreads

### ISSUE THREAD

**Issue by magnus-ISU** [mateusz-bak/openreads-android#166]
**Is your feature request related to a problem? Please describe.**
KoReader has no book discovery features. It would be cool if OpenReads would scan your files for an ebook named something like what you added, and/or allow you to specifically select a file which is a certain ebook, and then long-clicking it would open that book in a different reader app.

**Describe the solution you'd like**
When adding a book, have a different field for a path to a file which is the certain book.
It may be auto-filled by scanning the filesystem for anything with a similar name, as a stretch goal.
Long tapping the entry once the book has been added opens the book using the share menu

**Describe alternatives you've considered**
A different app having this functionality

**Comment by mateusz-bak** [comment]
Closing as it wil is definietely out of scope and event implemented will take resources to maintain the functionality.
