### ISSUE TITLE
[BUG] Empty book selection in 1.16/1.17

### ISSUE THREAD

**Issue by matthias4217** [mateusz-bak/openreads-android#167]
`Finished`, `In progress` and ` For later` tabs are empty. I've added many books, but none show up. After seeing #164 I went to the sort tab. No tag was ticked. I've toggled one, and the books with such a tag appeared in the right list. I then deactivated this tag (meaning that as before, no tag was ticked), and every book reappeared. This bug first appeared in `1.16` I think (though it might have been on 1.17, I think I've updated the app after encountering the bug).

**To Reproduce**

I don't know how to reproduce this, I'll see how it goes and if this issue happens again.

**Expected behavior**
Every book to appear in the various tabs.

**Additional info(please complete the following information):**
 - Manufacturer and model: LG G5
 - Android version: Android 11 (LineageOS 18.1)
 - App version: Currently 1.17.1-rc1, but I think the bug appeared on 1.16
 - App source (F-Droid, Google Play, Github): F-Droid

**Additional context**

I believe this bug may be a weird trick from my phone. I've opened this issue in case someone else had it as well. Seeing that OR and AND tag filters were implemented in 1.16, it may have had some weird uncontrolled effect ? (Though I have been on 1.16 without issue before.)

**Comment by mateusz-bak** [comment]
Hi @matthias4217 thanks for bringing that up. The sort implementation is not the best and will refactored as a part of the new 2.0 release this year. I will leave this open so we can check if issue is resolved then.

**Comment by mateusz-bak** [comment]
@matthias4217 please reopen if issue still occurs after 2.0.0 release.
