### ISSUE TITLE
[FEATURE_REQUEST] Select All/None button in the Sort UI

### ISSUE THREAD

**Issue by matthias4217** [mateusz-bak/openreads-android#168]
**Is your feature request related to a problem? Please describe.**
Related to #167, I wanted to select every or no tags, and as I have a dozen or so, it has taken a bit of time to select them all manually.

**Describe the solution you'd like**

 A "Select all tags"/Select no tags (and same for the years) button would be nice to have. My only concern is that it would mean cluttering the Sort tab.

Similarly, a "Invert selection" button could be useful.

**Describe alternatives you've considered**

Depending on how one manages tags, it's not necessarily too bad to select them manually.

Another way to improve my issue would be to have more of a "wall of tags", instead of a single scrollable line. This wall could be displayed via a "Show more" button.

**Additional context**

I don't think this is a high priority issue anyway, but I figured I should point this out.

**Comment by mateusz-bak** [comment]
I like the ideas, will try to implement them in 2.0+ release.

Anyway for now how this should work: if you don't select any tags and no years in the sort windows it will display all your books.

**Comment by mateusz-bak** [comment]
Alright I think `wall of tags` will clutter the UI too much. Same goes for the `Invert selection` button.

I will add `Select all` button at the end of years list and tags list. Let me know if you have any thoughts!

**Comment by mateusz-bak** [comment]
The buttons will be added in 2.2.0
