### ISSUE TITLE
[BUG] App makes noise when scanning a barcode

### ISSUE THREAD

**Issue by gdt** [mateusz-bak/openreads-android#171]
**Describe the bug**
The app makes noise when scanning a barcode, and obviously it should not.

**To Reproduce**
Install app.  Open.  Click through welcome screens.  Move to in progress.   Click add, select QR, click allow while using for camera.  Point camera at UPC on back of book.   See the barcode appear on the screen with something to push that says 'look up in openlibrary".  This is all good, and it's good that it didn't send it to the net without asking.   Note that the phone at the same time as showing the barcode made a really loud noise.

**Expected behavior**
I expected the scanning to be quiet because there is no reason for it to make noise.  In addition I looked in settings and there is no option to control this.  What if I were in a library, in a society where people still expected library behavior in libraries?

When I use QR & Barcode Scanner, it vibrates on detect, which I also consider a bug, but it's far less disturbing to others.

**Additional info(please complete the following information):**
 - Pixel, CalyxOS
 - App version: 1.17.2
 - App source: F-Droid

**Suggested Changes**
Just drop the noise, and don't even make an option.   The screen changing from scan target to showing the barcode is entirely enough feedback.   if you must, vibrate for 50 ms.   But apps should never make noise unless the user has asked them to make noise (music player) or to alert for an incoming message from a human (chat apps).

**Comment by mateusz-bak** [comment]
@gdt sound is removed, closing as fixed.
