### ISSUE TITLE
[BUG] Typo - License instead of licence

### ISSUE THREAD

**Issue by waot** [mateusz-bak/openreads-android#172]
See title

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional info(please complete the following information):**
 - Manufacturer and model:
 - Android version:
 - App version:
 - App source (F-Droid, Google Play, Github):
 
**Additional context**

**Comment by nobkd** [comment]
- **License** is both a noun and a verb in the United States.
- If you live in any other English-speaking country, you will spell it **licence** when you use it as a noun and **license** when you use it as a verb.

[Source](https://www.grammarly.com/blog/licence-license/)

**Comment by waot** [comment]
My apologies and thank you for teaching me, I guess I am too
american-centric for a european.

Kind regards and sorry to have wasted your time.

wout
