### ISSUE TITLE
[BUG] Backup file not being recognized as an Openreads backup file.

### ISSUE THREAD

**Issue by jmps117** [mateusz-bak/openreads-android#173]
**Describe the bug**
The backups I made of my Openreads data aren't being recognized as Openreads backups and as such aren't being restored from.

**To Reproduce**
I made 3 different backup files, none of them are recognized. I've tried it on a different device too and the same happens there.

**Expected behavior**
I expected the backup file to import the data to my new device.

**Additional info(please complete the following information):**
 - Manufacturer and model: Motorola One Action
 - Android version: 13
 - App version: 1.17.2
 - App source (F-Droid, Google Play, Github): F-Droid

**Additional context**
Apologies if this has been raised already, I did have a read through the issues but it's more than likely I missed something.

**Comment by kk6mrp** [comment]
I'm also having this issue on 1.7.3

**Comment by mateusz-bak** [comment]
@jmps117  @kk6mrp send the backups to my email. In app go to Settings -> Send Feedback

**Comment by Littlemogs** [comment]
> @jmps117 @kk6mrp send the backups to my email. In app go to Settings -> Send Feedback

I am having the same issue when uploading my backup to my one drive.
They are saving as 2 sql files (books & years) within a zip folder.
Can I email them over to you @mateusz-bak?

**Comment by Littlemogs** [comment]
@mateusz-bak email sent.

**Comment by jmps117** [comment]
Email sent :)
Also I tried out version 2.0.0 or Open Reads 2 and that imported the backup perfectly. Don't know if that helps you or anyone else.

**Comment by kk6mrp** [comment]
Just sent mine. Thanks!

**Comment by Littlemogs** [comment]
Any updates on this please? @mateusz-bak

**Comment by exstntlmsnthrp** [comment]
@mateusz-bak Backup file sent. Cheers.

**Comment by mateusz-bak** [comment]
Was unavailable past week, I'm looking at the files now

**Comment by exstntlmsnthrp** [comment]
I saw this issue and sent my file to you before I saw your comment/request on #183 even though mine is slightly different from this.

**Comment by mateusz-bak** [comment]
Thank you all for sending the files to my email, I checked them all. I spotted some issues with backups from 1.17 version but they all work perfectly on the 2.0 app. Also I fixed some issue with the backup from 2.0 -> 2.0. As this is fixes all that's left is to release 2.0 officially. 

I won't be implementing the fix in 1.x version as I will be releasing the 2.0 probably next week so you all should have the backups working.

I will leave this issue open and you can report if issues persists/ are gone after 2.0.0 release.

And remember the 2.0 version is not yet production ready so better to have your books in v2 for now and download 2.0 only for testing.

**Comment by jmps117** [comment]
Awesome, thanks for looking into this, I really appreciate it. I look forward to the new release!

**Comment by exstntlmsnthrp** [comment]
I agree. Thank you for all your hard work @mateusz-bak! This app is brilliant and I look forward to using the next version of the release. 🎉

**Comment by jmps117** [comment]
Sorry @brucetheelephant for taking so long to get back to you. I imported my original backups from app version 1.17.2 to version 2.0.0 rc1 and that worked for me. I haven't tested the import on rc2 or rc3.

**Comment by mateusz-bak** [comment]
@brucetheelephant I think I replied to your email now. The file name was not original and it caused the error. Looks like we are clear to release1

**Comment by mateusz-bak** [comment]
Closing this as 2.0.0 is released. Please reopen if issue still occurs
