### ISSUE TITLE
[FEATURE_REQUEST] Ability to save quotes within listing of book

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [mateusz-bak/openreads-android#174]
Hi,
I think a feature where for each book you can add an object defined by attributes - quote, page number and note, would be quite welcome.

So if you come across an interesting quote in the book, you can add this object and write the quote, the page number and a small note for context.

One should be able to add multiple such quote objects per book.

**Comment by ericsomto** [comment]
This is Open reads not Goodreads

**Comment by mateusz-bak** [comment]
We have `Notes` field now - you can use this for saving quotes.
