### ISSUE TITLE
[FEATURE_REQUEST] Add import and export CSV feature

### ISSUE THREAD

**Issue by s0mt0chukwu** [mateusz-bak/openreads-android#175]
**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**
Import and export feature  in preferable file format such as json or csv file list of finished books , in progress and for later.

**Describe alternatives you've considered**
Using csv file format to input list of books I've read and plan to 
Kinda of stressful to do 
Goodreads don't even have this feature yet

**Comment by giles-davis** [comment]
Is an import via goodreads .csv feature on the cards? I'd love to be able to jump ship from goodreads, but I just can't fathom manually adding like ~1k books manually 😮‍💨

Most people in my reading community feel the same unfortunately.

**Comment by mateusz-bak** [comment]
@giles-davis yeah I'm working on it right now!

If you want you can send me your .csv file on the email provided in the feedback section of the app so I can make sure it works correctly with all your books.
