### ISSUE TITLE
[BUG] Can't replace image when adding book

### ISSUE THREAD

**Issue by unchartedpopsicle** [mateusz-bak/openreads-android#177]
When adding a new book, any attempt to replace the image fails. No errors, the image just doesn't change. I can replace it just fine when pressing edit after saving the book. This was also the case on the old version of the app, i think.

**To Reproduce**
Scan a barcode
Press "Add book"
Click the image
Choose another image from your files

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 6
 - Android version: 13 (GrapheneOS)
 - App version: 2.0.0-rc1
 - App source (F-Droid, Google Play, Github): Github

Thank you for the app! The rewrite has fixed all crashes for me.

**Comment by exstntlmsnthrp** [comment]
I am also having this issue.

**Comment by mateusz-bak** [comment]
Fixed, will be in 2.0.0-rc2

**Comment by unchartedpopsicle** [comment]
Working here as well.

**Comment by exstntlmsnthrp** [comment]
Yes, works for me too.
