### ISSUE TITLE
[BUG] Filters and sort only apply to the "Finished" category

### ISSUE THREAD

**Issue by unchartedpopsicle** [mateusz-bak/openreads-android#178]
**Describe the bug**
Sort/filter options have no effect on "In progress" or "For later" books, except for displaying page count when attempting to sort by pages.
Changing the tab order does not affect this. The books are always sorted by date added. It is possible to display tags in any category.

**To Reproduce**
Add some books
Go to Sort/filter in the triple dot menu
Activate any filter or sorting option.

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 6
 - Android version: 13 (GrapheneOS)
 - App version: 2.0.0-rc1
 - App source (F-Droid, Google Play, Github): Github

**Comment by mateusz-bak** [comment]
Fixed, will be in 2.0.0-rc2

In progress will be sorted when selected: author, title, pages, or start date sort.
For later will be sorted when selected: author, title, pages sort.

**Comment by unchartedpopsicle** [comment]
Confirmed fixed :)
