### ISSUE TITLE
[BUG] Editing books adds more "delete" options in the three dot menu

### ISSUE THREAD

**Issue by unchartedpopsicle** [mateusz-bak/openreads-android#179]
**Describe the bug**
A silly one :)
Editing a book adds more delete options to the three dot menu of that book. The entries go away if you leave the book entry. The amount of delete options seems to depend on how much you have edited.

**To Reproduce**
Go to a saved book
Press the three dot menu
Press "Edit"
(Optional) Edit something
Press "Save"
Press the three dot menu again.

**Screenshots**
![Screenshot_20230125-223245](https://user-images.githubusercontent.com/89985351/214698184-0fc3ddb0-3e16-4306-9a56-c065878eb923.png)
![Screenshot_20230125-223310](https://user-images.githubusercontent.com/89985351/214698258-65ca2a6b-cbe0-4a4d-8c8f-b0d564b267b4.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 6
 - Android version: 13 (GrapheneOS)
 - App version: 2.0.0-rc1
 - App source: Github

**Comment by mateusz-bak** [comment]
Indeed, a silly one 😄 thanks for testing the 2.0 and for reporting this as well as the other ones!

**Comment by mateusz-bak** [comment]
Fixed, will be in 2.0.0-rc2

**Comment by mateusz-bak** [comment]
Fixed, will be in 2.0.0-rc2

**Comment by unchartedpopsicle** [comment]
Seems to be working.
