### ISSUE TITLE
[BUG] Can't choose edition of Life of Pi

### ISSUE THREAD

**Issue by unchartedpopsicle** [mateusz-bak/openreads-android#180]
**Describe the bug**
When pressing "Choose edition" for Life of Pi (9781841953922) the app throws an error. This is happens consistently, so far only with this book.

**To Reproduce**
Search in Open Library for "9781841953922" or "Life of Pi"
Press "Choose edition" on the top result

**Expected behavior**
The app to show some of the 149 available editions and not error.

**Screenshots**
![Screenshot_20230126-182407](https://user-images.githubusercontent.com/89985351/214920480-0c4a1722-e4a1-4752-9a01-910c92fae449.png)
![Screenshot_20230126-182341](https://user-images.githubusercontent.com/89985351/214920606-358b05c5-16de-416e-911c-96f67c320b6e.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 6
 - Android version: 13 (GrapheneOS)
 - App version: 2.0.0-rc1
 - App source: Github

**Comment by mateusz-bak** [comment]
Fixed, will be in 2.0.0-rc2

**Comment by exstntlmsnthrp** [comment]
I'm still seeing this with multiple books in 2.0.0-rc2.

**Comment by unchartedpopsicle** [comment]
Don't know about other books, but Life of Pi works now.

**Comment by exstntlmsnthrp** [comment]
@mateusz-bak  I had about 4 different books today that would not let me choose the edition. For example, "Chicken and Rice" ISBN 9780241199077, says there are 6 versions, but shows none of them. I believe there are they many versions, I have 2 in my collection and have seen a third in person. Same problem regardless of search method (scanning or manual input).

**Comment by unchartedpopsicle** [comment]
@exstntlmsnthrp I have seen that, it's a different issue. Open Library only has [two editions for that book](https://openlibrary.org/books/OL28593373M/Chicken_and_Rice?mode=all), and they are nearly identical. The edition count in the app seems pretty consistently higher than the actual count.

**Comment by exstntlmsnthrp** [comment]
@mateusz-bak I see. So is the problem with Open Library and not the app?

Just curious, because I had a couple of other books do that as well.

**Comment by unchartedpopsicle** [comment]
I've seen it a few times as well. Rather than an issue, it seems the app just doesn't pull extra editions with little to no data from Open Library. That the app counts 6 editions does seem like a bug, unless I'm missing something.

**Comment by apobrt** [comment]
related to #323

**Comment by apobrt** [comment]
Fixed with the new 2.2.0 release by #340
