### ISSUE TITLE
[FEATURE_REQUEST] Adjust secondary sort

### ISSUE THREAD

**Issue by unchartedpopsicle** [mateusz-bak/openreads-android#181]
**Is your feature request related to a problem? Please describe.**
I'm not sure how secondary sorting is handled now, but it leads to out of order series when sorting by author.

**Describe the solution you'd like**
It seems best to me to sort by author, then date, then title. 

**Describe alternatives you've considered**
Sorting only by author and date would be problematic for frequent releases such as the screenshot. If the app saved full dates rather than year, that could be avoided.

**Additional context**
![Screenshot_20230130-094054](https://user-images.githubusercontent.com/89985351/215432326-610bf2d5-7445-49e0-b54f-41a1f9e00fe0.png)

Related: #125 #145 #150 #178

**Comment by apobrt** [comment]
I can take care of this
