### ISSUE TITLE
[BUG] Multiple delete options

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#182]
I now see that this is the same as #179 

**Describe the bug**
I went to exit a recently added book to my connection and there were two "delete" entries under edit. 

**To Reproduce**
Open a newly added book.
Click on three dots for popup to edit book. 

**Expected behavior**
That there is only one entry to delete a book. 

**Screenshots**
![Screenshot_20230204-191249](https://user-images.githubusercontent.com/57594290/216797958-453422f8-7765-4b8a-9d15-ee34a5008161.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 7 Pro
 - Android version: 13, January 2023 security patch 
 - App version: 2.0.0rc1
 - App source (F-Droid, Google Play, Github): Github

**Additional context**
I added about 40 new books to my collection in the app today and when editing several of them (but not all of them) this error occurred.

**Comment by mateusz-bak** [comment]
Fixed, will be in 2.0.0-rc2

**Comment by exstntlmsnthrp** [comment]
👍

**Comment by mateusz-bak** [comment]
Fix released in 2.0.0, please reopen if issue still occurs.
