### ISSUE TITLE
[BUG] Cannot restore backup file 

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#183]
**Describe the bug**
I added about 40 new books to my collection today and created a backup to make sure the were not any problems after seeing issues with bug #182 that I reported. When going to restore the newly created backup, I get an error of a format exception (see screenshot) and backup does not restore and now I've lost all the new books I added today.

**To Reproduce**
Clear cache and data for app.
Uninstall and reinstall app (optional, it happened before this step as well).
Restore backup created with version 2.0.0rc1.

**Expected behavior**
I expect the backup to be restored. 

**Screenshots**
![Screenshot_20230204-202832](https://user-images.githubusercontent.com/57594290/216798298-dbbb2ee8-39c4-47ec-9088-fcb401d69b32.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 7 Pro 
 - Android version: Android 13
 - App version: 2.0.0rc1
 - App source (F-Droid, Google Play, Github): GitHub

**Comment by mateusz-bak** [comment]
@exstntlmsnthrp can you send the backup to my email? It's in the app's settings under contact me. Reference issue number #183 in the title

**Comment by exstntlmsnthrp** [comment]
I sent it earlier today. Apologies, I didn't reference the issue number in my email, but did give you my username.

**Comment by exstntlmsnthrp** [comment]
Works again and I have my books back! Thanks!
