### ISSUE TITLE
[BUG] Statistics tab will not load

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#184]
**Describe the bug**
After adding about 40 new books to my collection today, I wanted to look at the statistics tab and it would not load. I don't know if it is related, but this only happened after adding new books AND creating a new backup. After this, the stats page would only show the spinning dots.

**To Reproduce**
Add new books
Create new backup
Click on statistics

**Expected behavior**
I expect that I could view my updated statistics. 

**Screenshots**
![Screenshot_20230204-193735](https://user-images.githubusercontent.com/57594290/216798443-1e709fc4-7483-4cac-b8c3-f8937ab1ecf1.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 7 Pro 
 - Android version: 13
 - App version: 2.0.0rc1
 - App source (F-Droid, Google Play, Github): GitHub

**Comment by mateusz-bak** [comment]
Did the statistics work before?

**Comment by exstntlmsnthrp** [comment]
Only one time. After I downloaded the app and imported from 1.17.2 it worked once. Since then, nothing. All I get is the spinning dots.

**Comment by exstntlmsnthrp** [comment]
It looks great now. Thanks!
