### ISSUE TITLE
[BUG] Selecting done book status does not automatically insert date

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#185]
**Describe the bug**
I don't know if this should be one multipart bug or two separate ones. 

When adding a new book and selecting "Done" book status, the app used to automatically insert today's date. This does not happen any longer. If "Done" is selected as a book status but a "Finish date" is not selected, the book does not show up in statistics. 

**To Reproduce**
Add a new book. 
Select "Done" for book status. 
Save book entry. 
Click on statistics and scroll to number of books. The number is the same as before entering the new book. 

**Expected behavior**
Selecting "Done" book status automatically inserts the current date. Additionally, any newly added book should be included in statistics regardless of what fields are completed or empty. 

**Screenshots**
Previous app version:
![Screenshot_20230204-213432](https://user-images.githubusercontent.com/57594290/216798903-d636ab5b-f382-4bb9-9cf2-09e3736ae9b9.png)

Current app version:
![Screenshot_20230204-213649](https://user-images.githubusercontent.com/57594290/216798929-c062486c-fc28-4771-a2bd-2b6c9b2b7aa5.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 7 Pro 
 - Android version: 13
 - App version: 2.0.0rc1
 - App source (F-Droid, Google Play, Github): GitHub

**Comment by mateusz-bak** [comment]
Done, will be a part of 2.0.0-rc2

**Comment by exstntlmsnthrp** [comment]
👍

**Comment by exstntlmsnthrp** [comment]
This works again! Thank you.
