### ISSUE TITLE
[FEATURE_REQUEST] Viewing statistics shows total book count regardless of status

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#186]
**Is your feature request related to a problem? Please describe.**
I have a fairly large collection of books (estimated over 3000) that I am slowly adding to the app. When viewing the statistics, it only shows the number of books in that reading status. 

**Describe the solution you'd like**
I would like to be able to see a total of all books, regardless of reading status. 

**Describe alternatives you've considered**
At the moment, I have set the status of all my books to "Done" to make sure the total shows up in stats.

**Comment by mateusz-bak** [comment]
Hi, I'm not planning to implement a total number of books - we will need to do the math 🎃
