### ISSUE TITLE
[FEATURE_REQUEST] Clicking on a tag brings up a list of all books with that tag

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#187]
**Is your feature request related to a problem? Please describe.**
I often use multiple tags for book entries. When viewing a book, I would like to be able to click a tag and have a new screen show up that lists all books with that tag. 

**Describe the solution you'd like**
Pretty much described above. 
When viewing a book like this:
![Screenshot_20230204-220709](https://user-images.githubusercontent.com/57594290/216799394-ce415d8e-b926-4c39-9971-ad5d7be328c0.png)
I want the tag below the publishing date to be clickable to show all books with that tag 

**Describe alternatives you've considered**
None at this time. There's no current way to search or organize by tag.

**Comment by vbouchet31** [comment]
I suspect that it can help solving the request #343 to group books to create series.

**Comment by mateusz-bak** [comment]
Added the option to display books with the tag after clicking it. (Same with showing same author books)
