### ISSUE TITLE
[FEATURE_REQUEST] Clicking on tag field shows a list of recently used tags

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#189]
**Is your feature request related to a problem? Please describe.**
I use a lot of tags for my books. When clicking on the tag field when adding a new book or editing a current book, of love if a list of the 3 or 5 most recently used tags showed up and could be selected, instead of having to necessarily type it again. 

**Describe the solution you'd like**
Basically explained above. 

**Describe alternatives you've considered**
None at this time as this does not exist in the app. 

But the way, thank you for a brilliant app! I really think it's wonderful and have been searching for an app like this for many, many years! Keep up the good work. If you ever add "pro" features that require payment or accept donations, I'd be willing to pay. Your effort and time as a developer is with it! Not to mention, I want to support open source devs.

**Comment by mateusz-bak** [comment]
Thank you for all the good words @exstntlmsnthrp 

In version 2.1 you will have suggestion of the tags while creating/editing books!

There won't by any pro versions but there are ways to donate :money_mouth_face:
