### ISSUE TITLE
[FEATURE_REQUEST] Integration with Jelu

### ISSUE THREAD

**Issue by Polarolouis** [mateusz-bak/openreads-android#190]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to have an OpenReads sync with Jelu (https://github.com/bayang/jelu).

I believe Jelu exposes an API that OpenReads could use to sync with.

**Describe alternatives you've considered**
Writing a script and have it parse the CSV from OpenReads and sync to Jelu.

Thank you for reading me

**Comment by mateusz-bak** [comment]
At this time I don't think integrating a backend will fit Openreads - due to complexity, time needed for implementation and maintenance. Also Openreads's biggest point is working offline with no connection to any servers for data storage.
