### ISSUE TITLE
[BUG] Duplicate setting entry

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#201]
**Describe the bug**
In the settings, when you click on "Display outlines in the UI", there is a double entry for "Show outlines".

**To Reproduce**
Open app
Go to settings
Tap on Display outlines in the UI 

**Expected behavior**
There would be options to show outlines or hide outlines

**Screenshots**
![Screenshot_20230210-160209](https://user-images.githubusercontent.com/57594290/218197459-186cc323-c3f6-4ae0-a5aa-3ced7381b796.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 7 Pro
 - Android version: 14
 - App version: 2.0.0-rc2
 - App source (F-Droid, Google Play, Github): GitHub

**Comment by mateusz-bak** [comment]
Thanks, fixed
