### ISSUE TITLE
[FEATURE_REQUEST] Feature to track pages

### ISSUE THREAD

**Issue by chromer030** [mateusz-bak/openreads-android#226]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Please add a feature to track how many pages are read and how many left to finish.

**Describe alternatives you've considered**

**Additional context**

**Comment by Black-StellarSpectrum** [comment]
Yup I came here to ask for this feature, for In progress books it's nice to have page tracker which can be directly editable via In progress tab (like Showly)

**Comment by Amolith** [comment]
It would also be nice if it could track percentage rather than just page count; eBooks with reflowed text don't have page counts that match up with the printed version.

**Comment by apobrt** [comment]
Duplicate of #61
