### ISSUE TITLE
[BUG] Small figures are crammed in the circular chart

### ISSUE THREAD

**Issue by PassionateG1t** [mateusz-bak/openreads-android#249]
“In progress” and “unfinished” categories only make 1% each which isn't enough to make them enough space in the chart.

**Screenshots**
![Fygryrjrbbehw](https://user-images.githubusercontent.com/107609269/229342586-5336b93a-741e-4008-92bc-9759caebbbd4.jpg)

**Comment by mateusz-bak** [comment]
Fixed in #291 will be released with the next version.
