### ISSUE TITLE
[BUG] Cannot restore backups in 2.0.3

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#252]
**Describe the bug**
App will not import backup from same version of the app. Migration fails. 

**To Reproduce**
Backup openreads database from version 2.0.3
Reset phone to factory settings.
Reinstall openreads app
Import backup

**Expected behavior**
I expect backup to be restored. 

**Screenshots**
![Screenshot_20230405-174210.png](https://user-images.githubusercontent.com/57594290/230218570-dc3a3714-6f92-45e8-8177-41f1094620ef.png)

![Screenshot_20230405-173119.png](https://user-images.githubusercontent.com/57594290/230218316-4a9bd7f6-99e6-444e-8d68-18e0e470804f.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Pixel 7 Pro
 - Android version: 13
 - App version: 2.0.3
 - App source (F-Droid, Google Play, Github): GitHub

**Comment by exstntlmsnthrp** [comment]
The books you see in the screenshot are from the 2.0.0rc3 version of the app.

**Comment by mateusz-bak** [comment]
Hi, thanks for the email, will take a look in a couple of days

**Comment by exstntlmsnthrp** [comment]
Thank you. Hopefully it will not need to happen for awhile, but appreciate understanding an alternative method to do this.

**Comment by mateusz-bak** [comment]
Issue will be resolved in v2.2.0. Backup restoration won't need to read the backup's filename.

**Comment by mateusz-bak** [comment]
I'm starting to release 2.2.0 version. When you test it let me know if there are any issues and reopen the ticket.

Just to be clear on how this is fixed - this will work correctly with backup files created since version 2.2.0. Previous backups should be loaded with the mentioned workaround and re-created in the new version.
