### ISSUE TITLE
[BUG] 1 pixel line at the bottom 

### ISSUE THREAD

**Issue by UncivilizedGhost** [mateusz-bak/openreads-android#258]
**Describe the bug**
A one pixel line appears at the bottom of the app

**To Reproduce**
 Open the app  

**Expected behavior**
No line at the bottom
**Screenshots**

![Screenshot_20230418-180004_Openreads.png](https://user-images.githubusercontent.com/70070770/232786082-8a10ebfc-5678-4913-bc98-49a65b13c63f.png)

![Screenshot_20230418-175952_Openreads.png](https://user-images.githubusercontent.com/70070770/232786081-10905354-51c4-41b9-987d-0e2b07d1f1a8.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 5
 - Android version: 13
 - App version: 2.03
 - App source (F-Droid, Google Play, Github):

**Additional context**

**Comment by mateusz-bak** [comment]
_It's not a bug, it's a feature_

Openreads is following Material 3 guidelines and the mentioned line is a part of `TabBar` called `divider`.

Number `4` on this page: https://m3.material.io/components/tabs/specs
