### ISSUE TITLE
[Feature request] Grid view

### ISSUE THREAD

**Issue by vbouchet31** [mateusz-bak/openreads-android#262]
I am not really using the rating feature. Most of the time, covers already show the author name and book title. I would love to have the option to display the library in a grid (ideally number of books per row to be configurable).

Thanks

**Comment by Black-StellarSpectrum** [comment]
Yes it'd be nice to have a bookshelf view like we have on moon+reader

**Comment by mateusz-bak** [comment]
Hi! Grid view done in #279 Will be released in next version, probably this week if I fix some translations issues.
