### ISSUE TITLE
[FEATURE_REQUEST] Fork of OpenReads for Movies: OpenFlicks, OpenFilms?

### ISSUE THREAD

**Issue by vodknuckles** [mateusz-bak/openreads-android#269]
I believe the form-factor of this app would lend itself very well to tracking other forms of media, such as movies. It could pull information from TheMovieDB (or IMDb, if that's possible) and would basically work exactly the same way as OpenReads does; tracking film titles, giving statistics / settings goals about average runtime or how many films one watched in a year, star ratings, tags, etc. I think would be a fun and helpful way to track one's movie watching.

PS: This app is wonderful and has been a huge motivating factor for my recent reading efforts. I use it everyday.

**Comment by mateusz-bak** [comment]
Sounds like a good idea! Though I'm not sure it qualifies as a feature request for Openreads :smile: 

I'll leave it here anyway in case someone looks for a project idea.

**Comment by atharen** [comment]
@vodknuckles If you don't mind relying on [Trakt](https://trakt.tv/), which itself relies on TMDB, there are 2 open-source apps which I would recommend:
- https://github.com/UweTrottmann/SeriesGuide
- https://github.com/michaldrabik/showly-2.0

**Comment by mateusz-bak** [comment]
Looks like there are two alternatives, although not fully Open Source. I invite all people that were interested in this ticket to move to the mentioned apps repos.
