### ISSUE TITLE
[BUG]Run failed : Could not find storage-1.3.0.aar (com.anggrayudi:storage:1.3.0). 

### ISSUE THREAD

**Issue by xue9122** [mateusz-bak/openreads-android#277]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform storage-1.3.0.aar (com.anggrayudi:storage:1.3.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find storage-1.3.0.aar (com.anggrayudi:storage:1.3.0).
        Searched in the following locations:

**Comment by mateusz-bak** [comment]
Hi @xue9122 Are you building latest master? Can you write the commands you use to build? And can you show me output of `flutter doctor`

**Comment by apobrt** [comment]
You are missing some important steps: can you first complete the steps failed showed to you by `flutter doctor`?
It seems unrelated to the app functionality...

**Comment by mateusz-bak** [comment]
@xue9122 is this issue still happening?

**Comment by mateusz-bak** [comment]
Closing as it doesn't look like it's project related
