### ISSUE TITLE
[FEATURE_REQUEST] Split APK Architectures

### ISSUE THREAD

**Issue by chromer030** [mateusz-bak/openreads-android#303]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Please split github release APK to each architecture (arm64, x86 etc)  + an universal apk (for fdroid) , like mpv-android :

Use case is for old devices and lower storage occupation.

Thanks.

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20230720_221905](https://github.com/FriesI23/mhabit/assets/13361552/a5d173ca-2abc-4c5c-8a06-d7dc66fec06c)

**Comment by mateusz-bak** [comment]
Sounds like an good idea, I'll see what I can do.

**Comment by chromer030** [comment]
It can be done via modifiying artifact tag in github action yaml :

```
      - name: Build APPBUNDLE
        run: flutter build appbundle --release
      - name: Build FAT-APK
        run: |
          flutter build apk --release
          md5sum build/app/outputs/flutter-apk/app-release.apk
      - name: Build APK
        run: flutter build apk --split-per-abi
      - name: Released
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: >
            build/app/outputs/bundle/release/app-release.aab,
            build/app/outputs/flutter-apk/app-release.apk,
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk,
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk,
            build/app/outputs/flutter-apk/app-x86_64-release.apk
          token: ${{ secrets.APP_RELEASE_TOKEN }}
```

**Comment by mateusz-bak** [comment]
I added action for building full apk and split apks for Github releases. Next release this should work!

I did not find anything that would allow me to setup it for F-Droid.
