### ISSUE TITLE
[FEATURE_REQUEST] Change/add a book format.

### ISSUE THREAD

**Issue by vohneitcx** [mateusz-bak/openreads-android#309]
**Is your feature request related to a problem? Please describe.**
Yes. One format of a book is incorrect, and lacks another option.

**Describe the solution you'd like**.
Please change the "Paper Book" into "**Paperback**" because the latter is the right term.

Also, please add a "**Hardcover**" option because paperbacks and hardcovers are different from each other in cover design, page count, cost, etc.

Another thing: book types should either be "**Fiction**" or "**Nonfiction**," while book _formats_ are the paperback, hardcover, etc.

Thank you! ❤️

**Additional context**
![IMG_20230726_114903](https://github.com/mateusz-bak/openreads-android/assets/140505964/f51bc147-4fd8-4c77-88fa-537819987cf7)

**Comment by vohneitcx** [comment]
Oh, my bad. It should be "**Paperback**."* One word only.

**Comment by vohneitcx** [comment]
Very much so.

**Comment by apobrt** [comment]
Indeed, it would be more correct to use those four wordings, but from the UX point of view I find it better as it is now: the distinction between paperback and hardcover seems to me more formal than useful.
I have included many books that I read years ago, of which I don't remember at all whether they were paperback or hardcover....

It is certainly important instead to be able to distinguish between the different mediums:
- book: paper
- e-book: digital
- audiobook: audio

What if paperback and hardcover were optional additional information that could be selected if "book" was set?

**Comment by mateusz-bak** [comment]
So @apobrt idea would look this:

Book format:
 - book 
             - paperback
             - hardcover
- e-book
- audiobook

Would that make sense @vohneitcx ? I understand the point where you would not remember if the book was paperback or hardcover.

**Comment by vohneitcx** [comment]
sorry for the late response.

i've reconsidered and thought that would be better as well! either way, i trust in whatever changes you @mateusz-bak do. thank you so much.

**Comment by mateusz-bak** [comment]
@vohneitcx alright then it is decided, thanks.

And yeah I can look into the font.

**Comment by mateusz-bak** [comment]
Book formats are now set to:
paperback, hardcover, ebook and audiobook. I didn't add the vague "paper" option now as this would complicate logic and UI

**Comment by mateusz-bak** [comment]
Add font Inter added as well
