### ISSUE TITLE
[FEATURE_REQUEST] Add a separate Notes or Comments field

### ISSUE THREAD

**Issue by OrionCrim** [mateusz-bak/openreads-android#310]
It would be nice to have a `Notes` or `Comments` field (separate from the review) that only exists within the app. I'm assuming the `Review` field gets pushed back to Open Library, so it would not be a good candidate for use.

The primary use case for me is to note the following two pieces of information; however, it shouldn't be constrained to this.
1. Where I heard about the book
2. Why I added it to my list

Having a long to-read list, it can be months or more before I make it to entries. With a `Notes` field, I can easily refer back to what interested me about the book.

**Comment by mateusz-bak** [comment]
Hi, we had a notes field in the past. I can add it back.

And to explaing - noting gets pushed back to Open Library. All the info you add is stored only on your device.

**Comment by OrionCrim** [comment]
That would be great, thank.
Also thanks for the update that it's a one-way interaction with Open Library. It was an assumption based only on the community usefulness of reviews.

**Comment by mateusz-bak** [comment]
I'm gonna implement the "Notes" field as discussed in the Matrix channel
