### ISSUE TITLE
[PROPOSAL] Change the app logo

### ISSUE THREAD

**Issue by armand-leguillou** [mateusz-bak/openreads-android#315]
**hello!**
could someone send me the original .svg file or document of the app icon/logo?
I would like to try to improve it!

thanks to all the developpers, it's a very great app!

**Comment by armand-leguillou** [comment]
thanks!!!

**Comment by armand-leguillou** [comment]
i already done something!
i try to homogenize the logo by use variations of the original green, and i create a monochrome one for the themed app icon for android.
send me feedback!

(english is not my first language so i may made mistakes)

![Openreads-Icon-Background](https://github.com/mateusz-bak/openreads-android/assets/78372784/8e8baf40-ed4f-4f0a-82d8-4def36f57ac9)
![Openreads-Icon-Foreground](https://github.com/mateusz-bak/openreads-android/assets/78372784/2dbb311a-034b-4a0e-b63c-e0b9fad524a8)
![Openreads-Icon-Monochrome](https://github.com/mateusz-bak/openreads-android/assets/78372784/8538fffa-80b8-4db2-bad5-a1783c990f35)
![Openreads-Icon](https://github.com/mateusz-bak/openreads-android/assets/78372784/04c60318-2524-4f2a-b89c-7588febb21b8)

**Comment by mateusz-bak** [comment]
Looks good! My points:

- do you think the logo could be improved by rounding some of the corners?
- and maybe the lines that are the "text" in the book could be more visible?

**Comment by armand-leguillou** [comment]
sure I will try that as soon as possible!

**Comment by armand-leguillou** [comment]
- [x] i rounded the corners
- [x] i make the low-opacity zones more visible
      + some improvements

i think it's a way better!

complete icon 👇
![Openreads-Icon](https://github.com/mateusz-bak/openreads-android/assets/78372784/0ec39e0e-89c5-44a5-bede-5df6222175e6)

foreground 👇
![Openreads-Icon-Foreground](https://github.com/mateusz-bak/openreads-android/assets/78372784/58e1f49d-373c-478d-a431-54cc3a00dc80)

background 👇
![Openreads-Icon-Background](https://github.com/mateusz-bak/openreads-android/assets/78372784/ea9c5fec-5756-4255-9743-5d0fd4fd8457)

monochrome version 👇
![Openreads-Icon-Monochrome](https://github.com/mateusz-bak/openreads-android/assets/78372784/581b6569-3e73-4368-ab08-596dd14a8f80)

**Comment by armand-leguillou** [comment]
thanks @apobrt!
I tried many times to understand the documentation about the adaptive icons but I still don't know what to exactly do.
I think that it needs a safe zone or something like that, so if someone can tell me what to export in which resolution, I'll be glad!

**Comment by apobrt** [comment]
A side note: I just discovered this service ([Kavita](https://github.com/Kareadita/Kavita)) that uses a very similar logo to the current one (https://github.com/Kareadita/Kavita/blob/develop/Logo/kavita.svg).
So, one reason more to update this one!

**Comment by ikanakova** [comment]
I suggest a logo:

![book-logo](https://github.com/mateusz-bak/openreads-android/assets/38765251/3cc93fa3-a1e0-4613-a077-db2d12d14cd2)

**Comment by mateusz-bak** [comment]
#351 is implementing the improved icons, thanks everyone! Will be released with 2.2.0.

@ikanakova I think it would be a too drastic change!

**Comment by armand-leguillou** [comment]
> It's Great 👍💯

thanks @saltsoftdrink!


> Current version is v2.3.0 where is monochrome icon?

i don't know haha

**Comment by mateusz-bak** [comment]
@saltsoftdrink @armand-leguillou waiting for someone to implement in #284

**Comment by mateusz-bak** [comment]
Not sure what is the issue here - #284 waits for someone to implement so you are welcome to contribute

**Comment by ikanakova** [comment]
@armand-leguillou Don't you have the foreground and monochrome icon in svg? I would make adaptive and monochrome icons, but I think it needs to be vector.

**Comment by sebastien46** [comment]
> Not sure what is the issue here - #284 waits for someone to implement so you are welcome to contribute

Icon needs to be a VectorDrawable to be Themed, not possible with a Bitmap.
you'd need a source SVG file in order to do that.

**Comment by armand-leguillou** [comment]
if the svg are needed for the monochrome icon:

![couleur](https://github.com/mateusz-bak/openreads/assets/78372784/cf0988c1-a8a7-477c-bb43-3f353c3be4fc)
![monochrome](https://github.com/mateusz-bak/openreads/assets/78372784/0b23e274-3f31-4b79-b823-96b0a1ef75b8)
