### ISSUE TITLE
[FEATURE_REQUEST] Automatically search on OpenLibrary when nothing is found with barcode

### ISSUE THREAD

**Issue by jrom99** [mateusz-bak/openreads-android#319]
**Is your feature request related to a problem? Please describe.**
When you scan an ISBN barcode and no book is found, it currently shows an empty screen.

**Describe the solution you'd like**
It should show the button to add that book manually (and autofill the ISBN field) and the button to search on OpenLibrary (should the user be ok with having the wrong edition).
I think this would help streamline the user experience, and make it easier to add new editions to OpenLibrary if that feature lands.

**Describe alternatives you've considered**
It could automatically change to search on OpenLibrary or manually add the book, but I think that would be too opinionated.

**Additional context**
Current screen:
![Screenshot_2023-08-25-13-42-46-172_software.mdev.bookstracker.jpg](https://github.com/mateusz-bak/openreads-android/assets/47498278/8c829270-43d0-4535-bf07-c32f272c5ed2)

**Comment by mateusz-bak** [comment]
I like the "add manually" option when no books found.

But I don't understand this part: `and the button to search on OpenLibrary `.
You are already in the Open Library search screen and the `Search` button _is_ `the button to search on OpenLibrary`

**Comment by jrom99** [comment]
>You are already in the Open Library search screen and the Search button is the button to search on OpenLibrary

I had only used ISBNs while searching, so I didn't know you could search by title, TIL.

Do you think adding a book manually with autofill would still be doable in this case? Without validating the input or knowing that the user came from the scan barcode screen, I'm not sure how one could know the kind of input data used.

**Comment by mateusz-bak** [comment]
Yeah, I can add a button to add a book manually when no records from Open Library. And it can have the ISBN autofilled, sounds doable.

**Comment by greaterthanstar** [comment]
good

**Comment by mateusz-bak** [comment]
The text "No items found" is now clickable and depending on what type of search is used (title, author or ISBN - new feature since 2.4.0) a field will be auto-filled in the Add Book Screen
