### ISSUE TITLE
[BUG] This is not a valid openreads backup error

### ISSUE THREAD

**Issue by exstntlmsnthrp** [mateusz-bak/openreads-android#322]
**Describe the bug**
I upgraded the app to version 2.1.0 and my books were gone. When attempting to restore from two separate backups, I get an error message "this is not a valid openreads backup." I then get a message saying the backup was successfully restored. 

**To Reproduce**
Download update (both 2.1.0 and 2.1.0rc1 have the problem) directly from GitHub. 
Restore previous backup. 

**Expected behavior**
I expect my existing books to remain. I also expect the backup to be restored.

**Screenshots**

![Screenshot_20230906-151248_Trebuchet.png](https://github.com/mateusz-bak/openreads-android/assets/57594290/d46547ae-a603-4599-a24e-6eac1fd4b27a)

![Screenshot_20230906-151316_Trebuchet.png](https://github.com/mateusz-bak/openreads-android/assets/57594290/b02e115b-3af5-4f83-8387-9feb20ac1a30)

**Additional info(please complete the following information):**
 - Manufacturer and model: pixel 7 pro
 - Android version: lineageos 20 (android 13)
 - App version: 2.1.0 and 2.1.0rc1
 - App source (F-Droid, Google Play, Github): GitHub

**Additional context**

I don't know if this is related to #243 or if this is a different problem.

**Comment by exstntlmsnthrp** [comment]
Anyone? Thoughts or ideas?

**Comment by mateusz-bak** [comment]
Hi, is it different that #252? Is the workaround not working?

**Comment by exstntlmsnthrp** [comment]
That's very bizarre. I tried that several times based on that discussion and couldn't get it to work. 

This time, I uninstalled and reinstalled and restore worked. I cannot understand why it didn't before. 

Thanks.

**Comment by mateusz-bak** [comment]
Glad it worked, anyway I'm doing a fix so it won't be an issue soon.
