### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by jontaix** [mateusz-bak/openreads-android#33]
I want to translate to Portuguese (Brasil).
Is there any weblate, crowndin, something like that?
Or should I translate the strings.xml and send a PR?

**Comment by mondlicht-und-sterne** [comment]
> I want to translate to Portuguese (Brasil). Is there any weblate, crowndin, something like that? Or should I translate the strings.xml and send a PR?

I would like to know that too ;)

**Comment by mateusz-bak** [comment]
@jontaix @mondlicht-und-sterne I haven't yet set any system for that. I'm looking at this right now - Crowdin looks promising as it is free for FOSS projects, but I need some time to see how this works. A PR is always welcome, but I should be able to set a system for that today/tomorrow. Thank you for the input!

**Comment by mateusz-bak** [comment]
@jontaix @mondlicht-und-sterne I set up Crowdin: [https://crwd.in/openreads-android](https://crwd.in/openreads-android) Feel free to contribute and let me know if there are any issues.

**Comment by jontaix** [comment]
Thanks, I'm translating.

**Comment by comradekingu** [comment]
@mateusz-bak 
Crowdin has never been gratis for open source. It is free of charge for non-commercial open source projects.
Moreover, it isn't good, and I guess we have established as much in trying it out.
Close it down the sooner the better. It creates a lot of issues by getting locales wrong, etc.

**Comment by mateusz-bak** [comment]
@comradekingu what is your recommendation? I had some issues with Crowdin and I'm currently setting up Weblate https://hosted.weblate.org/projects/openreads

**Comment by comradekingu** [comment]
That is exactly what I would do. You can add "kingu" and I can have a look at the setup. :)

**Comment by xmgz** [comment]
Please would it be possible to upgrade roles in weblate so suggestions can be approved by selected users in each language?

It's been a while since I improved my own translation but this changes are not merged.

thank you
