### ISSUE TITLE
Allow change date display format [FEATURE_REQUEST] 

### ISSUE THREAD

**Issue by w1ll1am23** [mateusz-bak/openreads-android#334]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Display dates based on system region. I'm located in the US so seeing dd/mm/yyyy is confusing would be nice to have it displayed as mm/dd/yyyy

**Describe alternatives you've considered**
Allow manually setting the preferred format. 

**Additional context**

**Comment by mateusz-bak** [comment]
Dates will be displayed following language defaults. WIll be released in 2.3.0
