### ISSUE TITLE
[FEATURE_REQUEST] Add publisher agent and publisher date below covers in the choosing edition grid

### ISSUE THREAD

**Issue by apobrt** [mateusz-bak/openreads-android#341]
**Is your feature request related to a problem? Please describe.**
The page of choose of the edition of a book shows a grid of covers, which graphically helps a bit to understand what we want to pick, but it is not enough

**Describe the solution you'd like**
Would be super helpful to have, below the cover, the labels of the publisher and of the publishing date (if present, of course)

**Describe alternatives you've considered**
I think the first option is simple and effective enough.

**Additional context**
An example (forgive my editing skills..)

![Screenshot_20230928_224607](https://github.com/mateusz-bak/openreads-android/assets/45424365/ef9830b4-e2e1-47d5-847f-9280fd9e4bf5)

**Comment by th8m0z** [comment]
I have implemented this, with the proposal to reduce the crossAxisCount to 2, so that the UI does not look so cramped.

<img width="349" alt="Bildschirmfoto 2024-01-22 um 17 51 33" src="https://github.com/mateusz-bak/openreads-android/assets/41947147/a9a944e3-e833-4330-bc70-2db1f0003bfc">
