### ISSUE TITLE
[FEATURE_REQUEST] Sort edition results

### ISSUE THREAD

**Issue by apobrt** [mateusz-bak/openreads-android#342]
**Is your feature request related to a problem? Please describe.**
When choosing the edition of a book, they are displayed in a grid in no particular order (it's in fact the one return by Open Library). But this means that often the "best" result (the one with more information/the most updated) are somewhere in the middle

**Describe the solution you'd like**
After fetching the results from Open Library, before displaying them, sorting them :
- by language (firstly the ones with the same language of the user), then
- by release date (the last ones first)

It is even clearer if #341 is implemented

**Comment by Kreuger** [comment]
I would like to easily see the ISBN because sometimes they dont match up.

**Comment by apobrt** [comment]
> I would like to easily see the ISBN because sometimes they dont match up.

You probably meant to write in https://github.com/mateusz-bak/openreads-android/issues/341 😉

**Comment by mateusz-bak** [comment]
I don't see any option to get the editions sorted by any means from Open Library.

The book from search has a list of editions predefined and Openreads is getting them in that particular order.

If you spot how this can be implemented differently please reopen and explain
