### ISSUE TITLE
[FEATURE_REQUEST] Display a fallback image when there is no cover 

### ISSUE THREAD

**Issue by apobrt** [mateusz-bak/openreads-android#346]
**Is your feature request related to a problem? Please describe.**
Some editions don't have a cover image, so a black box with the writing "no cover" is shown, which is ugly.

**Describe the solution you'd like**
It's better to show a fallback, stock, image

**Additional context**
It is necessary since https://github.com/mateusz-bak/openreads-android/pull/340, because before the editions without a cover weren't shown.

**Comment by mateusz-bak** [comment]
I think that we either could:
- keep the no cover text,
- remove the text but indicate the lack of the cover (a colored background or something).

I wouldn't show any stock images of covers or the default book cover because that could mislead the user.

**Comment by vbouchet31** [comment]
My proposal would be a coloured or a blurry background (a little bit like behind the covers when viewing / editing a book) with the author name and book name hover it. I would keep the colors/blur very neutral.
