### ISSUE TITLE
Cannot restore backup [BUG] 

### ISSUE THREAD

**Issue by loic5032** [mateusz-bak/openreads-android#347]
**Describe the bug**
I'm switching to another phone. I can't restore the backup I made on my previous phone.

**To Reproduce**
Steps to reproduce the behavior: make backup on one phone then restore backup on other phone. An error message appears saying "This is not a valid openreads backup" then a message says "backup restored" but nothing is restored.

**Expected behavior**
All my books should be restored as the were. 

**Additional info(please complete the following information):**
 - Manufacturer and model: Google pixel 5
 - Android version: 14
 - App version: 2.1.0
 - App source (F-Droid, Google Play, Github): tried both F-droid and Google play

![Screenshot_20231021-115117](https://github.com/mateusz-bak/openreads-android/assets/78465427/990fd14b-40cb-4ae3-8d83-1d69bd723bca)
![Screenshot_20231021-115110](https://github.com/mateusz-bak/openreads-android/assets/78465427/5963dd6b-1ec8-4043-8912-046b4aa56dcc)
![Screenshot_20231021-115104](https://github.com/mateusz-bak/openreads-android/assets/78465427/70effd2c-f5f4-491c-804f-d6955509851e)

**Comment by mateusz-bak** [comment]
Hi, issue already discuees in #252. Please look there for workaround before 2.2.0 release
