### ISSUE TITLE
[FEATURE_REQUEST] Bulk edit

### ISSUE THREAD

**Issue by vbouchet31** [mateusz-bak/openreads-android#349]
**Is your feature request related to a problem? Please describe.**
I want to apply the same edit to multiple books at the same time.

**Describe the solution you'd like**
Long "click" on a book adds it to the selection. The action buttons at the top (search, view mode, dots) are replaced by a pencil. When clicking, it opens a lightweight version of the book edit form (not all the book attributes are relevant for bulk update). Saving the form apply the edition to all the selected books.

**Additional context**
I just discovered the book type (paper, ebook, audio) attribute. Editing each and every book individually is painful.

**Comment by mateusz-bak** [comment]
Currently bulk edit is implemented for book format. Do you think anything else should be there as well?

**Comment by vbouchet31** [comment]
I am not sure to get if you are saying it is already or that you worked on it and it will be part of the next release. Whatever is the answer, thank you for replying to my suggestion ;-).

I am wondering about the author (for example I get sometime "Harlan Coben", "Harlan COBEN", "H. Coben", ...).
Maybe bulk edit for the tag make sense as well.

**Comment by mateusz-bak** [comment]
Yeah this is implemented as per 2.2.0 version.
Alright so editing author as well.
