### ISSUE TITLE
Document the format required for a CSV import.

### ISSUE THREAD

**Issue by bananabob** [mateusz-bak/openreads-android#350]
I currently have my read books list in an SQL database on my home server. I would like to export the contents of this database into a CSV and then import it into Openreads.

Please can you document the required format for a CSV file import. Which columns should be included and what the names of the columns should be.

Thank you!

**Comment by mateusz-bak** [comment]
Right now importing Goodreads CSV should work.

**Comment by apobrt** [comment]
I try: maybe, now that an export feature is live, we can make an "official" OpenReads CSV format (the same of the export), so other apps/services/people can export to this format.
The end goal, in my mind, should be to make inter-operability better.

But yes, in the meantime, @bananabob you can follow the Goodreads format and use the corresponding import capability

**Comment by bananabob** [comment]
@apobrt What is the Goodreads format? Can't seem to find the explanation. Secondly I can't find where the import feature is in the app. I know it is there but where is it hiding?

**Comment by apobrt** [comment]
I can't find online an official documentation of how the Goodreads is structured, but if you made one, you can get from it. 
I think also that @mateusz-bak can answer more precisely to that.

The import feature is located under Settings > Backup and restore > Import Goodreads CSV (I know, find it under backup is not so obvious).
Be aware that **is present only in the last release, the 2.2.0,** so be sure to have it updated!

![image](https://github.com/mateusz-bak/openreads-android/assets/45424365/c0acc9c6-b622-4c5c-beda-6ed4a6d05b55)

**Comment by mateusz-bak** [comment]
Exactly what @apobrt said. 

And I didn't find any Goodreads documentation on CSV just had people email me their exports. I can look for one tomorrow and show you how it is structured.

**Comment by bananabob** [comment]
> I can't find online an official documentation of how the Goodreads is structured, but if you made one, you can get from it. I think also that @mateusz-bak can answer more precisely to that.
> 
> The import feature is located under Settings > Backup and restore > Import Goodreads CSV (I know, find it under backup is not so obvious). Be aware that **is present only in the last release, the 2.2.0,** so be sure to have it updated!
> 
That would explain why I can't find it. I have the latest version available from F-Droid 2.1.0. I can wait for the update. Also I see from your image that you can export a CSV. That is good. The best way I can find the format required would be to do just that.

**Comment by mateusz-bak** [comment]
@bananabob  Unfortunately no, as per 2.2.0 you can export CSV in let's say Openreads format but import only Goodreads CSV

**Comment by mateusz-bak** [comment]
@bananabob  fortunately with 2.3.0 release there will be the option to import Openreads CSV! And the required format is here: https://github.com/mateusz-bak/openreads-android/blob/master/doc/csv.md
