### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Barmarel** [mateusz-bak/openreads-android#36]
Please make these items appear as a grid.
![40963e9c-c744-48c8-9c40-de8f944fc5d7.jpg](https://user-images.githubusercontent.com/60399684/161180984-eb29b61a-506a-4dfb-8d07-48d5035f271f.jpg)

Also, please add a field for entering Genres and a field for entering Annotations.

**Comment by mateusz-bak** [comment]
@Barmarel do you have something like this in mind for the grid? (with option to switch list-grid view)

 <img src="https://user-images.githubusercontent.com/32651935/161835344-7f873f6d-bee3-48f7-83ca-0910fdbbff46.jpg" width="300">

And for the Annotations, is "Notes" field not enough? Or maybe I should just rename Notes to Annotations?

**Comment by Barmarel** [comment]
• Yes, that's the kind of grid we need.
• I would still like a separate field for annotations, because annotations may be needed for other information.

**Comment by Barmarel** [comment]
There are a couple more requests/suggestions:
- Please add the ability to specify not only the date, but also the start and end time of the book reading.
- And please add the ability to specify/change the number of pages already read in a book. (You can also do some kind of progress bar based on this data, it would be cool).

**Comment by Barmarel** [comment]
Another thing I noticed, I have a couple of books with a lot of authors, and after adding a book, some of these authors are trimmed. Apparently not enough character limit...

**Comment by mateusz-bak** [comment]
@Barmarel thanks for all the inputs! I added the grid layout and increased limit of title and characters, v.1.13.0 should be in store in next couple of hours.

About those suggestions:
> There are a couple more requests/suggestions:
> 
>     * Please add the ability to specify not only the date, but also the start and end time of the book reading.
> 
>     * And please add the ability to specify/change the number of pages already read in a book. (You can also do some kind of progress bar based on this data, it would be cool).

I added them to backlog, but don't plan to release in v1.14.0. (You can check out the current progress here [Roadmap](https://github.com/mateusz-bak/openreads-android/projects/18))

**Comment by Barmarel** [comment]
Спасибо 😃.
