### ISSUE TITLE
[BUG] Reading Time incorrect, needs +1 offset

### ISSUE THREAD

**Issue by pandalamp** [mateusz-bak/openreads-android#366]
**Describe the bug**
Reading time is counted from 0 instead of 1. This value needs to be offset by +1 to account for the first day.

**To Reproduce**
Set start/finish dates one day apart and observe the Reading Time will report "1 day" versus the 2 days actually spanned (first day + next day) 

**Expected behavior**
Reading Time should report the number of days spanned while reading instead of the difference between them. If I start and finish a book on the same day, my reading time should be listed as "1 day."

**Comment by mateusz-bak** [comment]
Thanks, makes sense to correct that
