### ISSUE TITLE
[BUG] Date picker should regard values already entered

### ISSUE THREAD

**Issue by jannis701** [mateusz-bak/openreads-android#369]
**Describe the bug**
If I want to select a date, which was already set before (because I already set it in the form and want to change it, or because I am editing an entry in which this value is already set), the default-value of the picker is always the current date and not the date which was already set for this field. this is confusing and unnecessary complicated to enter

**To Reproduce**
Steps to reproduce the behavior: add a new entry for a book (manually). change "start date" to some other date than today. open the date-picker for "start date" again. the date-picker (or the text-field for setting the date) will have the value of the current date as default-value

**Expected behavior**
the date-picker (or the text-field) should have the default-value of the already entered data.
Additionally it would be nice, if you start editing one of the date-fields "start date"/"end date" when it is empty and the second field of the two is already set, then the picker should start with the value of the second (already set) field

**Additional info(please complete the following information):**
 - Manufacturer and model: Samsung Galaxy S5
 - Android version: 11
 - App version: 2.2.0
 - App source (F-Droid, Google Play, Github): F-Droid

**Additional context**

**Comment by McBaumwolle** [comment]
I agree. I recently logged some books from two years ago and this was really annoying at times.

**Comment by mateusz-bak** [comment]
Thanks for raising the issue, will fix it.
