### ISSUE TITLE
[BUG] Date display/input format mismatch

### ISSUE THREAD

**Issue by Woebin** [mateusz-bak/openreads-android#370]
**Describe the bug**
Reading dates are shown in dd/mm/yyyy format, but when changing the date via input (i.e. not using the calendar element) it's parsed as mm/dd/yyyy.

**To Reproduce**
1. Open details view on a book in your collection.
2. Go into edit mode.
3. Edit "finished reading" date.
4. Hit the pen icon to switch from calendar view to manual input.
5. Input date, e.g. "12/01/2020".
6. "Finished reading" date is now set to the first of December, 2020, and displayed as "01/12/2020".

**Expected behavior**
Expected input format should match display format.

**Screenshots**
Will provide on requires if the description isn't clear enough.

**Additional info(please complete the following information):**
 - Manufacturer and model: OnePlus A6013
 - Android version: 11
 - App version: 2.2.0
 - App source (F-Droid, Google Play, Github): GitHub via Obtainium 

**Additional context**
Ideally, date format should be up to the user and not locked into any default. Whichever format is used should be consistent throughout the app (input and display should match).

**Comment by ngocanhtve** [comment]
Same issue for me

**Comment by magnus-ISU** [comment]
It would be nice if you could choose a date format, either

mm/dd/yyyy
dd/mm/yyyy
yyyy-mm-dd

**Comment by mateusz-bak** [comment]
Thanks for raising. I suppose @magnus-ISU suggestion with allowing user to choose the format will work the best.

**Comment by mateusz-bak** [comment]
Alright, from now on the displayed dates (in book screen, in the list etc) will follow devices format (same as the one in date picker)
