### ISSUE TITLE
[FEATURE_REQUEST] More obvious when filtering books

### ISSUE THREAD

**Issue by orangecorn** [mateusz-bak/openreads-android#379]
I loaded up the app, went into the finished tab and there were no books there. I panicked that I had lost my data, but after a minute I realised I had it filtering by a tag that is only present in my for later section.

To stop this from happening to anyone else, I think there should be text that goes underneath the app title when filtering books. e.g. 'filtering by tag **Books I own**'
In my opinion, this will make the UX much better.

It could also be toggleable in the 'appearance' tab in settings for those who don't like it.

**Comment by mateusz-bak** [comment]
As part of other request I added a counter of the books being show and all books in the list. It should resolve your issue without cluttering the UI much.

![obraz](https://github.com/mateusz-bak/openreads-android/assets/32651935/c951304d-df2a-4e7c-9c2c-86e91ff650b1)
