### ISSUE TITLE
[FEATURE_REQUEST] Sync with OpenLibrary

### ISSUE THREAD

**Issue by thisisartman** [mateusz-bak/openreads-android#389]
Any books added here would sync to OpenLibrary. 
In similar fashion to how Tachiyomi syncs Manga with Anilist.

**Comment by mateusz-bak** [comment]
I think this is a duplicate to https://github.com/mateusz-bak/openreads-android/issues/54

If you have any thoughts on how this could be implemented please add info in the mentioned ticket. Im not familiar with Tachiyomi and Anilist unfortunately.

**Comment by thisisartman** [comment]
> I think this is a duplicate to https://github.com/mateusz-bak/openreads-android/issues/54

Yes, it's the same.

> If you have any thoughts on how this could be implemented please add info in the mentioned ticket. Im not familiar with Tachiyomi and Anilist unfortunately.

[Tachiyomi](https://github.com/tachiyomiorg/tachiyomi) is a manga reader app that allows syncing with various services. [Anilist](www.anilist.co) is an anime and manga tracking site.

They have a Tracking section in the settings, that lets you log into the preferred service. They sync the information every 12hrs I believe. Here's how their page looks:

![Screenshot_20231129-170856.png](https://github.com/mateusz-bak/openreads-android/assets/85949613/995cbf1d-730d-480c-9861-de793608baf6)
