### ISSUE TITLE
[FEATURE_REQUEST] Add a "Did not finish" status

### ISSUE THREAD

**Issue by starryveshch** [mateusz-bak/openreads-android#39]
**Is your feature request related to a problem? Please describe.**

Sometimes I don't finish a book, but I like to keep it just to revisit it in the future.

**Describe the solution you'd like**

Adding a "Did not finish" tab similar to the other book status tabs.

**Comment by mateusz-bak** [comment]
Hi @starryveshch good idea! I will add did not finish status but probably wont add it as a tab (more than 3 tabs will couse the labels to not be displayed fully). I can add this as a position in settings same as trash or add as an option in three dor menu. What do you think?

**Comment by starryveshch** [comment]
> I can add this as a position in settings same as trash or add as an option in three dor menu. What do you think?

Adding it to the three dot menu would be good. Can you also make it have similar filtering and sorting functionality?

**Comment by mateusz-bak** [comment]
> > I can add this as a position in settings same as trash or add as an option in three dor menu. What do you think?
> 
> Adding it to the three dot menu would be good. Can you also make it have similar filtering and sorting functionality?

Yeah, I think so. I will add the page first and add the filter/sort later. (with the holidays I have currently less time for this but I'm always happy when I have new ideas ;)

**Comment by mateusz-bak** [comment]
Hi, I added the "not finished" status to the app, will release probably at the enf of this week!
