### ISSUE TITLE
[BUG] On new installation,  navbar blocks the Start button 

### ISSUE THREAD

**Issue by majkaz** [mateusz-bak/openreads-android#391]
See picture, first install of v. 2.2 on Android 13.

After I clicked it in split screen mode, it seems only the very first screen has this problem. 

Seems to be introduced in the last version...

![Screenshot_20231129_214554](https://github.com/mateusz-bak/openreads-android/assets/23097386/16917de6-3ee4-48db-8712-b69816e46e78)

**Comment by mateusz-bak** [comment]
Nothing was changed there in the last version, but the Flutter was upgraded so maybe the framework introduced some changes.

Just so I understand it correctly. Does this happen when Openreads is reduced to 50% of the screen or something? Does this function normally when back to full screen?

**Comment by mateusz-bak** [comment]
I see looks like I need to move the button out of the nav bar area
