### ISSUE TITLE
[BUG] Display Tags only works in List view

### ISSUE THREAD

**Issue by PrivacyFriendlyMuffins** [mateusz-bak/openreads-android#404]
**Describe the bug**
In *Sort / filter*, under "Filter by tags", the option "Display tags" shows tags under each book entry in List view, but not in Thumbnail mode.

**To Reproduce**

1. Make at least 1 tag.
2. Apply tag to at least 1 book.
3. Tap "Sort / filter" in top-right hamburger menu.
4. Under "Filter by tags", toggle "Display tags".

**Expected behavior**
In Thumbnail view mode, each book entry should have either a tag listed underneath it or as an overlay.

**Screenshots**

![Screenshot_20231209-211850-628](https://github.com/mateusz-bak/openreads-android/assets/86497467/5c5c0194-59e3-47cd-b092-8d525b125ba9)

![Screenshot_20231209-211144](https://github.com/mateusz-bak/openreads-android/assets/86497467/5cfbd7e9-098a-4f42-ac16-95acda7bdd38)

![Screenshot_20231209-211149](https://github.com/mateusz-bak/openreads-android/assets/86497467/4caa6317-de7a-4b71-9370-9e3366bc06cc)

**Additional info(please complete the following information):**
- App version: 2.3.0
- App source (F-Droid, Google Play, Github, AppStore): F-Droid
- Manufacturer and model: Motorola One 5G Ace
- OS and version: Android 11

**Additional context**

**Comment by mateusz-bak** [comment]
Hi, sorry that you find it as an issue but that is intented behavior.

The list view is for details and grid for visual.
