### ISSUE TITLE
[FEATURE_REQUEST] Use https for all connections to Open Library

### ISSUE THREAD

**Issue by zyores** [mateusz-bak/openreads-android#405]
**Is your feature request related to a problem? Please describe.**
Not all connections between the phone and Open Library are encrypted via TLS. The initial search for ISBN, title or author is using plain http.

**Describe the solution you'd like**
Although there are no credentials transferred between the phone and Open Library, I do think that all TCP connections should nowadays be encrypted via TLS.

**Comment by mateusz-bak** [comment]
Good catch, all connections should be https now
