### ISSUE TITLE
[FEATURE_REQUEST] Move "Unfinished books" into the main section of the app

### ISSUE THREAD

**Issue by acbarker19** [mateusz-bak/openreads-android#418]
**Is your feature request related to a problem? Please describe.**
The "Unfinished books" list is currently inside the app settings. While the "Deleted books" list makes a bit of sense in the settings, this does not seem like the most intuitive place to search for books that were started but not completed.

**Describe the solution you'd like**
The "Unfinished books" should be brought into the main pages of the app so the user has access to all the books they've read in one place. One possible solution would be to have the "Finished" tab contain both completed and incomplete books. The list could add a label or symbol to mark incomplete books and have a filter to select Completed, Incomplete, and Both. If both statuses are moved into the "Finished" tab, some language may need to change in the app for clarity, such as the status buttons for books could be changed to "Completed" and "Incomplete" instead of "Finished" and "Unfinished".

**Describe alternatives you've considered**
A new tab could be introduced to the main section of the app so it would now be "Finished", "Unfinished", "In progress", and "For later". However, this may make the tab buttons appear a bit crowded on some screens. If this route is taken, some tab buttons may need to wrap onto two lines.

**Additional context**
Thanks for reading my suggestion! Please let me know if there are any questions or feedback.

**Comment by apobrt** [comment]
I like the idea, I find it unintuitive to search the unfinished books into the settings.
I add another possible way: adding it to the top menu (the three dots)

**Comment by mateusz-bak** [comment]
Hi, thanks for raising an issue that you would like to have faster access to unfinished books.

I like @apobrt 's solution about the three dot menu. Seems like an easy enough change - will do it in some time but anyone is welcome to implement.

**Comment by acbarker19** [comment]
I think the 3 dot menu would work fine for the idea and is likely a better solution than what I originally suggested. I was having a hard time finding the right place within the main app to put the unfinished books. Thanks for the feedback and accepting it!

**Comment by th8m0z** [comment]
I have just added a PR for this

**Comment by mateusz-bak** [comment]
Completed, thanks!
