### ISSUE TITLE
[FEATURE_REQUEST] Cover selection

### ISSUE THREAD

**Issue by rYR79435** [mateusz-bak/openreads-android#42]
**Is your feature request related to a problem? Please describe.**
Sometimes books on OpenLibrary have multiple covers uploaded to them. It would be nice if I can select which one I want.

**Describe the solution you'd like**
A modal that displays all availbale covers (if there are any).

**Comment by mateusz-bak** [comment]
Hi @rYR79435 thanks for the suggestion!
I tried to find books with multiple covers on OpenLibrary but couldn't, do you have an example for that?
Or are you talking about different editions?

Anyway I'm thinking of adding a dialog as you said for selecting a cover from ones avaibale in OL.

**Comment by rYR79435** [comment]
This one has https://openlibrary.org/books/OL7359256M/Nineteen_Eighty-Four

Although looking at it without being logged in, I can't see them. Only when I log in do they appear under "Manage Covers". I'm not sure if this is possible.

**Comment by mateusz-bak** [comment]
I found it in the API (covers section), do you see two covers there?

Link to API: https://openlibrary.org/books/OL7359256M.json
[cover 1](https://covers.openlibrary.org/b/id/108160-L.jpg) [cover 2](https://covers.openlibrary.org/b/id/12725652-L.jpg)

And for example this one has 12 covers: https://openlibrary.org/works/OL45883W.json

Currently I pull only the first cover, but I think I can add option to  select from the rest of them if they exist.

**Comment by rYR79435** [comment]
Nice!
Since multiple covers were not showing on the web page, I was worried they would only be available while logged in. Glad the API provides them.

**Comment by mateusz-bak** [comment]
@rYR79435 search is refactored now and should be easier to add correct cover/edition.
