### ISSUE TITLE
[FEATURE_REQUEST]  AI Book Suggestions

### ISSUE THREAD

**Issue by th8m0z** [mateusz-bak/openreads-android#422]
**Is your feature request related to a problem? Please describe.**
I always struggle with finding new books to read and would love a way for this app to generate book suggestions based on books I select or have already read. This would help me discover new things I might like.

**Describe the solution you'd like**
Either a screen where users can input titles of books and use a embeddings / a vector database to search across all books to find similar ones. Maybe this could even be done automatically based on books users have already read.

**Describe alternatives you've considered**
There are some websites that do something similar, but I have not seen any open source apps that accomplish this.

**Additional context**
I would love to contribute and tackle this feature myself, just give me a quick heads up that I'm good to go and this is something you would also like to see.

**Comment by th8m0z** [comment]
A simple version of this would just be a query to GPT-3.5 asking for 3 new books based on books already read or inputted. More involved would be an embeddings database, with data from OpenLibrary. Is one of the solutions feasible for openreads @mateusz-bak? Just give me a quick thumbs up and I'll get to work with a PR.

**Comment by mateusz-bak** [comment]
Is it possible to implement the feature with Open Source tools and services? I'm not so sure unfortunately but I will be happy to be proven otherwise.

**Comment by th8m0z** [comment]
Would it be okay to let users input their OpenAI key? That would definitely make things easier.

**Comment by visuelledata** [comment]
There is [OpenLLaMa](https://huggingface.co/openlm-research/open_llama_13b/blob/main/README.md), however, I have no idea if it is practical to implement in a mobile app.

**Comment by mateusz-bak** [comment]
I don't think this will be an good idea too @visuelledata 

I'm closing it as not planned as this would be too complicated for such a small app.
