### ISSUE TITLE
[FEATURE_REQUEST] Wishlist

### ISSUE THREAD

**Issue by ikanakova** [mateusz-bak/openreads-android#425]
**Is your feature request related to a problem? Please describe.**
I like the For Later tab because I use it, for example, when I'm reading a series, so I'll prepare the next book in series here. It bothers me a bit that I have to put books I want to read someday (but not in the near future) here, and then they get mixed in with the ones I want to read in next days.

**Describe the solution you'd like**
I'd like it if, in addition to the For Later tab, there was a Wishlist tab where users could put books they're interested in and might want to read someday.

**Describe alternatives you've considered**

**Additional context**

**Comment by urmomseksy** [comment]
Wouldn't this be a good use of tags?

**Comment by ikanakova** [comment]
> Wouldn't this be a good use of tags?

I think tags are more for distinguishing genres, but if it were possible to filter based on tags (for example, show everything except...) then tags could be used as well.

**Comment by mateusz-bak** [comment]
I also think tags are suitable for this use case. When you filter by tags you have a toggle for tags filter mode.

For example if you select filtering by tags `history` and `wishlist` you can either display books that have both tags set up or at least one of them set up.

**Comment by mateusz-bak** [comment]
@ikanakova yes I added the functionality to show books without a tag now, will be released in 2.4.0

https://github.com/mateusz-bak/openreads-android/pull/432
