### ISSUE TITLE
[FEATURE_REQUEST]Show and quickly edit progress

### ISSUE THREAD

**Issue by EAlZZZl** [mateusz-bak/openreads-android#426]
Google Translate:

 **Is your feature request related to a problem? Please describe.**
 There is no progress display when creating video and online novel records, and the number of episodes watched cannot be quickly changed.

 **Describe the solution you'd like**
 Add a [+1] button to the right or lower right corner of the 12-episode video of "In Progress". When clicked, "1/12" and a progress bar will be displayed or only 1/12 will be displayed.

**Comment by mateusz-bak** [comment]
Sorry I don't understand the request here

**Comment by EAlZZZl** [comment]
> Sorry I don't understand the request here

Google Translate: 
Something like this.  But if you click the button once, you will be marked as having watched 1 episode, and if you click it twice, you will be marked as having watched 2 episodes.
![Screenshot_20240124-225730_Translator.png](https://github.com/mateusz-bak/openreads-android/assets/130824184/e9391d8c-1a82-4ea4-a1c7-51a6cead9382)

**Comment by ikanakova** [comment]
> Are you sure this is a request for Openreads app?

Can't he want the same thing as in #61?

**Comment by EAlZZZl** [comment]
> Are you sure this is a request for Openreads app? Screenshots shows something different

What I want to say is: adding this progress bar ui and quick +1 makes 1/12 become 2/12

**Comment by ikanakova** [comment]
> > Are you sure this is a request for Openreads app? Screenshots shows something different
> 
> What I want to say is: adding this progress bar ui and quick +1 makes 1/12 become 2/12

I think we understand that you want add progress bar, but it's not clear what you think a progress bar is supposed to do when you're **keeping track of your books**.

**Comment by EAlZZZl** [comment]
> > > Are you sure this is a request for Openreads app? Screenshots shows something different
> > 
> > What I want to say is: adding this progress bar ui and quick +1 makes 1/12 become 2/12
> 
> I think we understand that you want add progress bar, but it's not clear what you think a progress bar is supposed to do when you're **keeping track of your books**. You mean quickly mark a book that's In Progress as Finished?

What I mean is: tracking about 12 episodes of TV series, videos, or online novels with about 500 chapters.  Then click [+1] after watching an episode or chapter to simplify the process.  Mainly used for: websites that do not support progress recording; streaming media or online novels are removed or banned; some websites lose progress or change the progress unintentionally; previews of new dramas, new videos, and new novels that you are interested in, but the website  Unable to follow due to reasons such as not being put on the shelves

**Comment by ikanakova** [comment]
Openreads is actually a [reading journal](https://www.masterclass.com/articles/reading-journal-ideas) (kind of like [Goodreads](https://www.goodreads.com/)), so it's definitely not for tracking TV shows and videos. If it's for online short stories then this could be considered a duplicate to issue #61.

**Comment by mateusz-bak** [comment]
I agree with @ikanakova . If this is relevant to #61 please add information there.
