### ISSUE TITLE
[BUG] Tags wont show up

### ISSUE THREAD

**Issue by Git08hb** [mateusz-bak/openreads-android#437]
**Describe the bug**
When i enable "display tags" the tags wont show up even tough i gave that book a Tag and hit save. When I click on edit again the tag isn't there anymore so it probably doesn't even save the tag.

**Expected behavior**
Tags showing up after enabling "Display Tags"

**Screenshots**
![Screenshot_20240128-161458](https://github.com/mateusz-bak/openreads-android/assets/97441502/d282603b-6c4f-4a21-94fa-9fa09b329e5c)

![Screenshot_20240128-161513](https://github.com/mateusz-bak/openreads-android/assets/97441502/fe2a043f-92d1-4886-bb82-241c57d9fe71)

**Additional info(please complete the following information):**
- App version: 2.3.0
- App source: F-Droid
- Manufacturer and model: Google Pixel 6
- OS and version: GrapheneOS (Android 14)

**Comment by mateusz-bak** [comment]
When you add a new tag while editing book details,  you need to click "submit" on your keyboard to save the tag. If you just type it and do not click "enter" the new tag is not saved.

**Comment by Git08hb** [comment]
> When you add a new tag while editing book details, you need to click "submit" on your keyboard to save the tag. If you just type it and do not click "enter" the new tag is not saved.

That worked thank you lol....
