### ISSUE TITLE
[BUG] Adding an empty tag leads to an exception

### ISSUE THREAD

**Issue by th8m0z** [mateusz-bak/openreads-android#446]
**Describe the bug**
Adding an empty tag leads to an exception.

**To Reproduce**
Add an empty tag to a book.

**Expected behavior**
It should not add a tag at all but simply dismiss the keyboard.

**Additional info(please complete the following information):**
- App version: 2.4.0
- App source: Github
- Manufacturer and model: iPhone 15 Pro
- OS and version: iOS 17.0

**Additional context**
Can work on it, it seems like there is a problem in this segment: `
    if (tag.substring(tag.length - 1) == ' ') {
      tag = tag.substring(0, tag.length - 1);
    }`

**Comment by mateusz-bak** [comment]
Thanks for reporting, I will do a quick fix before releasing 2.4.0 today.
