### ISSUE TITLE
[BUG] Incorrect icon button spacing in the 'In Progress' and 'For Later' categories

### ISSUE THREAD

**Issue by GitFincy** [mateusz-bak/openreads-android#53]
**Describe the bug**
The 'Edit', 'Delete', and 'Grid/List Layout' buttons are squeezed together for books in the 'In Progress' and 'For later' section.

**To Reproduce**
Add a book in the 'In Progress' or 'For Later' category.
Click on the book you added.
You will see the three icon buttons squeezed together, making it difficult to click the specific button you want.

**Expected behavior**
The three buttons are nicely spread out, just like books that are in the 'Finished' section (however, without the heart/favourite icon)

**Screenshots**
Correct icon spacing in the 'Finished' section:
https://i.imgur.com/NuvmFzM.png

Incorrect icon spacing in the 'In Progress' section:
https://i.imgur.com/9wsbb7s.png

Incorrect icon spacing in the 'For Later' section:
https://i.imgur.com/n1tbXEl.png

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 5
 - Android version: 12 (+ 5 April 2022 security update) on GrapheneOS
 - App version: 1.13.0
 - App source (F-Droid, Google Play, Github): Droid-ify (An F-Droid client https://github.com/NeoApplications/Neo-Store)

**Additional context**
I did not try to reproduce the bug with cover images added to my entries. All my entries did not have covers added to them.

**Comment by mateusz-bak** [comment]
Hi @GitFincy , I've been able to reproduce this issue on my phone. I will include fix in the next update.
Thanks for contribution!

P.S. Did you say you installed app from F-Droid? I'm still waiting for them to include my app

**Comment by GitFincy** [comment]
Oh, I got it from IzzyOnDroid (https://apt.izzysoft.de/fdroid/index/apk/software.mdev.bookstracker), sorry for the confusion.

Thank you for creating Openreads!

**Comment by mateusz-bak** [comment]
Fixed, will release probably at the end of the week.
