### ISSUE TITLE
[BUG]  Adding a cover picture from file does not work

### ISSUE THREAD

**Issue by Toraquin** [mateusz-bak/openreads-android#56]
**Describe the bug**
While adding a book manually I tried to add a cover picture. The app does offer taking a picture or upload it from local files. Choosing "take a picture", the app requests Android permissions for the camera, choosing "upload from file" nothing happens.

**To Reproduce**
Add a book manually, choose "click to add cover" and "upload cover from local files"

**Expected behavior**
The app should aks for storage permissions and allow me to choose a picture as the cover picture

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 6
 - Android version: 12 (GrapheneOS, based on a hardened AOSP)
 - App version: 1.13
 - App source: F-Droid

Looking forward to some improvements of the app, I already like it very much!

**Comment by mateusz-bak** [comment]
Hello, thank tou for the contribution. I did some changes with permissions when adding a F-Droid release and mistakenly blocked the covers. Will fix the changes and release soon.

**Comment by mateusz-bak** [comment]
Fixed, will release probably at the end of the week.
