### ISSUE TITLE
[FEATURE_REQUEST] Import Books From GoodReads CSV

### ISSUE THREAD

**Issue by tootbrute** [mateusz-bak/openreads-android#57]
**Is your feature request related to a problem? Please describe.**
To make this a great alternative for those who have years of GoodReads.com book data, it would be amazing to be able to import the books I've read from a GoodReads CSV.

**Describe the solution you'd like**
- person downloads the CSV from GoodReads
- person opens the CSV in OpenReads
- OpenReads adds the books to the correct list - read, to read, did not finish etc.
- any books that fail to be added - mark them somehow? or guess what books they could be? I wouldn't want to lose track of which books were successfully imported, and which weren't. Maybe output a CSV of books that failed? Then the person could add these books manually.

**Describe alternatives you've considered**
I would never use this app without being able to import all my books into it. I have considered BookWyrm but I don't really need all the social aspects of that solution.

**Additional context**

**Comment by grubeli** [comment]
I was looking for a Goodreads alternative for a while now, I think this app is very promising!

If you could add option to import from Goodreads would be amazing

**Comment by mateusz-bak** [comment]
Hello @tootbrute @mizzunet @grubeli thank you for the suggestion! I can see that this can be a helpful feature, I will work on this and release soon.

**Comment by mateusz-bak** [comment]
@tootbrute @mizzunet @grubeli @pionaiki @shbach @krillin666 @jakubnewcomb

Can you help me with testing the CSV import functionality? If yes please follow below steps:

1. **Create a backup of your current books** 
Preferably in a cloud, if local then move the files out of `Local Storage/Android/data/software.mdev.bookstracker/files` In case of reinstall of the app you lose files there - so move the backups to for example `Downloads` folder (I'm working on doing it more handy but storage in Android is messy).
2. **Download Openreads v1.15.0-rc1 from [here](https://github.com/mateusz-bak/openreads-android/releases/tag/v1.15.0-rc1) and install on your phone**
If you have app installed from other sources like Google Play or F-Droid you might need to uninstall it first so **remember about the backup!**
3. **Prepare your `.csv` file from Goodreads on your phone's local storage**
[Here](https://help.goodreads.com/s/article/How-do-I-import-or-export-my-books-1553870934590) is how to get the file.
4. Go to `settings/backup` in freshly installed  Openreads and select `Import books from CSV`. Now choose the `.csv` file.
5. Tell me if you have any issues here or if the process went OK.

I never used Goodreads so my knowledge about every use case may be limited.
Thank you all for the support!

**Comment by pionaiki** [comment]
@mateusz-bak 

I've imported my `.csv` and it worked, unfortunately, without the `Date started` but I am aware that's Goodreads' fault as they don't include it in the export.

I also have two suggestions:
- "Shelves" and tags in Goodreads are kind of the same thing so to import the tags (which are currently not imported) the app should use everything from the `Bookshelves` csv column minus the item in the `Exclusive Shelf`.
- The default shelves in GR are `read`, `currently-reading` and `to-read`, these work correctly in the import but, aside from these three, many people have a shelf called `abandoned` ([because that's a suggestion when creating a custom shelf](https://user-images.githubusercontent.com/51377752/170892593-d5e608ed-9b6f-46d4-9bde-aef98d810758.png)), I think that, even though that's not a default in GR, books from `abandoned` should go to `Not finished books` in Openreads.

**Comment by tootbrute** [comment]
I just did it. Wow! Looks great.

Of my 2174 books in my CSV it uploaded all but 6.

A quick scan of my books I assume these ones were not added:
- 2 had no title
- 1 was arabic title
- 3 had greek titles

**Comment by mateusz-bak** [comment]
Thanks all for checking!

@pionaiki would you mind sharing couple of examples from `Bookshelves`  `Exclusive Shelf` columns so I can have a better picture how this works? And for point if `abandoned` is not default just suggested maybe I can add parsing of shelves and the user would select a specific shelf for `not finsihed` in Openreads?

@mizzunet the changelog sometimes shows unnecessary, I will need to go through the code and fix it, submitted an issue for now #94 and can you raise a feature request for the books conuting? We had this option before but it was removed when I added tab layout for lists

@tootbrute I wonder where those 6 disappeared. Maybe they got imported but are not shown somehow. It might be impossible to spot those 6 in 2174 books but maybe you can open your csv on your computer in a spreadsheet, and filter out any anomalies with shelv, or date columns? And the covers unfortunately are not being saved into the csv, it's just plan text.

**Comment by pionaiki** [comment]
@mateusz-bak 

> And for point if `abandoned` is not default just suggested maybe I can add parsing of shelves and the user would select a specific shelf for `not finsihed` in Openreads?

That's a good idea.

Here is a screenshot of my csv:
![Screenshot](https://user-images.githubusercontent.com/51377752/170975567-27035e12-aa06-41f5-b3ad-cadd9bb59b98.png)

So for example in the 8th line `lang-polish` and `school` are tags and `abandoned` is the shelf because it shows in both columns.

**Comment by mateusz-bak** [comment]
@pionaiki to clarify, is the `abandoned` a shelf because it is in the `Exclusive shelf` column or because it is on both of them? I ask because I'm not sure if I just parse the `Exclusive shelf` and see what shelves we have there except the default three or I need to compare with `Bookshelves` column also.

**Comment by pionaiki** [comment]
@mateusz-bak 

It's the shelf because it's the one in the Exlusive shelf and everything from the Shelves except the one is tags

**Comment by mateusz-bak** [comment]
@tootbrute @mizzunet @grubeli @pionaiki @shbach @krillin666 @jakubnewcomb

Please check v1.15.0-rc2 updated now with recognizing book tags and unfinished status. Waiting for your feedback!
[v1.15.0-rc2](https://github.com/mateusz-bak/openreads-android/releases/tag/v1.15.0-rc2)

[Here](https://github.com/mateusz-bak/openreads-android/issues/57#issuecomment-1140525928) are instructions and don't forget about the backup!

**Comment by mateusz-bak** [comment]
@tootbrute @mizzunet @grubeli @pionaiki @shbach @krillin666 @jakubnewcomb

Please check v1.15.0-rc2 updated now with recognizing book tags and unfinished status. Waiting for your feedback!
[v1.15.0-rc2](https://github.com/mateusz-bak/openreads-android/releases/tag/v1.15.0-rc2)

[Here](https://github.com/mateusz-bak/openreads-android/issues/57#issuecomment-1140525928) are instructions and don't forget about the backup!

**Comment by jakubnewcomb** [comment]
My app crashes when I try to import a csv.

**Comment by mateusz-bak** [comment]
@jakubnewcomb would you mind sharing your csv with my in private?

**Comment by mateusz-bak** [comment]
@mizzunet the to read books import fine with isbn for me, can you send on an example book from csv that got importet without ISBN?

**Comment by mateusz-bak** [comment]
@tootbrute yeah the covers are a bummer... And I could identify those 26 books and fix the algorithm I you could share your csv with ke in private.

**Comment by tootbrute** [comment]
> @tootbrute yeah the covers are a bummer... And I could identify those 26 books and fix the algorithm I you could share your csv with ke in private. `mateusz.bak.dev@gmail.com`

sent. hope it helps improve the algorithm! thanks for including this feature i finally have no excuse to leave goodreads.

**Comment by mateusz-bak** [comment]
@mizzunet yeah that books don't have ISBN in the CSV so no issue with the import. Do they have ISBN in Goodreads? Thanks for the csv!

**Comment by mateusz-bak** [comment]
@tootbrute and everyone who has some time to check if nothing got broken

Please check v1.15.0-rc3 updated now with recognizing not finished books in statistics, improved the "unfinished bookshelf" dialog when importing csv and improved readability of pie chart. Waiting for your feedback!
[v1.15.0-rc3](https://github.com/mateusz-bak/openreads-android/releases/tag/v1.15.0-rc3)

[Here](https://github.com/mateusz-bak/openreads-android/issues/57#issuecomment-1140525928) are instructions and don't forget about the backup!

@jakubnewcomb would be awesome to check your csv why it crashes the app

**Comment by ashwebcode** [comment]
Tried v1.15.0-rc3 and it worked great for me @mateusz-bak. I'm officially deleting my Goodreads account 👍

**Comment by mateusz-bak** [comment]
@jakubnewcomb I tried the csv you send to me and the import is successful on my device. 

Can you please confirm below questions:
1. Is there only one book in the csv?
2. You click 1Import books from CSV` in settings and choose the correct file
3. You use 1.15.0-rc3 version

**Comment by mateusz-bak** [comment]
@kanado01 glad you were able to do that, would be awesome though to see what was the original problem.

I figured a way we can see what is causing the crash.

Can you install v1.15.0-rc4? I added a possibility to send an email with logs after app crashes.

Please follow the backup [steps](https://github.com/mateusz-bak/openreads-android/issues/57#issuecomment-1140525928), download v1.15.0-rc4 from [here](https://github.com/mateusz-bak/openreads-android/releases/tag/v1.15.0-rc4) and import your original csv.

When app crashes you will see a dialog asking you to send an email, you need to click OK there and you will be redirected to your email app. Crash logs should be attached, my email should be prefilled (unless you use protonmail like me and there's a bug so please manually type `mateusz.bak.dev@gmail.com`)

Thanks!

**Comment by ashwebcode** [comment]
I noticed the imported books don't have a cover, even for the ones it has the ISBN. Is there a way to easily add the covers?

**Comment by tootbrute** [comment]
> adding covers

I was also curious about that. I know it would involve lots of manual work but would really be the cherry on top after switching.

**Comment by mateusz-bak** [comment]
@kanado01 okay then, let's hope it was only some local issue!
@ashwebcode @tootbrute unfortunately as csv has only text it can't have covers imported. Workaround would be to automatically download covers but I'm not sure how this should choose the edition for now. I will by implementing anyway adding covers from Open Library to existing books so you can get covers after the import!

**Comment by mateusz-bak** [comment]
@pionaiki @mizzunet @tootbrute @ashwebcode @kanado01 @grubeli @lazerleif @shbach @krillin666

Thank you all for the support! Csv import has been implemented in the newly released v1.15.0. It is available to download from Github now, should be in Google Play in 1-2 hours and in F-Droid in couple of days. Cheers!

**Comment by robsonsobral** [comment]
Is it possible to add a list of field names to the readme, please?

**Comment by mateusz-bak** [comment]
> Is it possible to add a list of field names to the readme, please?

What do you mean, list of columns in Openreads database?

**Comment by robsonsobral** [comment]
Yeap, @mateusz-bak ! I'm trying to import from Storygraph, but the field names are a little different from Goodreads.

**Comment by digfish** [comment]
It appears in the 2.0 version there's no option to import the goodreads csv.

**Comment by mateusz-bak** [comment]
Yeah, it's on to do list to recover the functionality. I'll posted here when it's ready.
