### ISSUE TITLE
[FEATURE_REQUEST] Koreader integration?

### ISSUE THREAD

**Issue by SmutnyStefan** [mateusz-bak/openreads-android#58]
**Is your feature request related to a problem? Please describe.**
Koreader is one of the most popular ebook readers for both e-ink and standard android devices. Alas it does not have a management tool that would allow me to integrate both physical books and ebooks
I would like the ability to pull out the book status and metadata from Koreader

**Additional context**
I am not a programmer so I don't know if It can be done, but I know Koreader is a plugable program, so maybe you could create a Koreader plugin of some sort for your program that would allow to send the data out? I have literally hundreds of ebooks, so manually retyping the data is a huge pain

**Comment by Atrate** [comment]
[Koreader repo link](https://github.com/koreader/koreader/)

A plugin is one way to do it, another would be for Openreads to process the koreader stats databases/book metadata files directly, they contain various stats such as book start/finish times, time read per day, time spent per page, ratings, reviews etc.

**Comment by BalooRJ1** [comment]
I would also like to see this, even though I run koreader on an ereader and not on the same android phone as openreads. If the developer of openreads can, koreader also has an active github and is available on many platforms. mobileread.com also has many resources related to koreader.

**Comment by apobrt** [comment]
I've never used, so maybe it exists a better solution, but if Koreader can export the book list into a csv/json, it would be possible to import the data into Openreads

**Comment by mateusz-bak** [comment]
After consideration I don't think integration with Koreader will be implemented. Openreads is just a simple app for offline book tracking without much information and I don't have that much time to adopt and maintain the integration. 

If anyone wants I'm more that happy to add CSV import from Koreader if I'm being provided an example file.
