### ISSUE TITLE
[BUG] Books without ISBN are not shown

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [mateusz-bak/openreads-android#62]
**Describe the bug**
Continuing from https://github.com/mateusz-bak/openreads-android/issues/60 
Books without ISBN are shown in search results.

**To Reproduce**
1. Open the App
2. Press the + Floating button in any tab and select "Search in Open Library"
3. Try "சோஷலிசம்"

**Expected behavior**
Should be able to see books without ISBN and add them to the list.

**Comment by mateusz-bak** [comment]
Hi @PrasannaVenkadesh thank you for spotting that! I will take a look a this today.

**Comment by mateusz-bak** [comment]
@PrasannaVenkadesh I spotted the issue and added workarounds for adding books without ISBN, thanks for showing me that. Will release the fix around the weekend.
