### ISSUE TITLE
[FEATURE_REQUEST] Transparent navbar (edge to edge)

### ISSUE THREAD

**Issue by b3il0** [mateusz-bak/openreads-android#63]
I know a lot of Android apps are having this in black, but maybe consider doing a transparent navbar (edge to edge) for a better experience.

https://developer.android.com/training/gestures/edge-to-edge

**Comment by mateusz-bak** [comment]
Hi @b3il0 thanks for the idea! Although I'm not sure if I see the use case here. If we are talking about the `Status Bar` - what would be the befit here if in every screen we have `App Bar` (with title and buttons) at the very top so this should not be behind `Status Bar`. 
And for `Navigation Bar` - in books list at the top we have the `Tabs` which should not be behind `Navigation Bar`. The only use I see is transparent `Navigation Bar` when displaying book's details or in statistics and settings.

Did I get it correctly? What are your thoughts?

**Comment by b3il0** [comment]
Greetings @mateusz-bak sorry for the confusion with the link. I was only referring to the color of the system navbar. It is black in your app and if you made it transparent, it would also be white in light mode but black in dark mode.

I've attached an image where I made the navbar transparent to show what I mean.

![Screenshot_20220518-172327](https://user-images.githubusercontent.com/37301674/169091833-1f5eb5cf-1ed7-4cfb-9e51-377d31508af0.jpg)
.

**Comment by mateusz-bak** [comment]
@b3il0 changed the nav bar to transparent. Looks good on the emulator with gesture navigation in light and dark mode and in 3 button navigation in dark mode (in light mode it is grey on the emulator though - but still better than black).

I was a little confused for some time and then discovered that when I don't set the nav bar to transparent it is black in emulator and white on my phone with 3 buttons navigation (OnePlus does this to prevent screen burn in). Works fine with gestures

Will be implemented in v1.16.0
