### ISSUE TITLE
[FEATURE_REQUEST] Sync with Calibre

### ISSUE THREAD

**Issue by Victor239** [mateusz-bak/openreads-android#65]
**Is your feature request related to a problem? Please describe.**
Calibre has a great interface for managing book progress on desktop but not so great on mobile compared to OpenReads. It would be useful to have them both sync together so book progress can be synced.

**Describe the solution you'd like**
Ability to sync with Calibre via Calibre content server or calibre-web

**Describe alternatives you've considered**
Some way to access OpenReads as a web app perhaps

**Comment by mateusz-bak** [comment]
Hi @Victor239 thanks for the idea, I don't know Calibre much. I will check how it works and see if this can be implemented.

**Comment by mateusz-bak** [comment]
At this time I don't think integrating a backend like Calibre will fit Openreads - due to complexity, time needed for implementation and maintenance. Also Openreads's biggest point is working offline with no connection to any servers for data storage.
