### ISSUE TITLE
[BUG] Backup unsuccesfull when user has ~80 books

### ISSUE THREAD

**Issue by jphouston** [mateusz-bak/openreads-android#81]
**Describe the bug**
When I try to backup the database to either cloud or local storage, the app crashes after showing the loading wheel.  It only started this behavior when I had added more books to the app. I have tried quiting and restarting and this did not fix the issue. 

**To Reproduce**
Settings - Backup - Cloud Backup / Local Backup 

**Expected behavior**
App either opens the file manager or opens the share menu to select a cloud storage app. 

**Screenshots**
![Screenshot_20220523-114209_1](https://user-images.githubusercontent.com/106042696/169727793-65a3e397-7c6c-486b-bb96-c0bfb98e3ad2.png)

**Additional info(please complete the following information):**
 - Manufacturer and model: Google Pixel 4 XL
 - Android version: 12
 - App version: 1.14.0
 - App source (F-Droid, Google Play, Github): Github APK

**Additional context**

**Comment by mateusz-bak** [comment]
Hello @jphouston thanks for reporting that. How many books do you have in your app and how many of them with a cover?

**Comment by jphouston** [comment]
About 80 books, all with cover photos. That does give me an idea. I'll try deleting the ones with a cover photo I've taken myself as they might be uncompressed and quite large.

**Comment by mateusz-bak** [comment]
@jphouston please try v1.14.2

**Comment by jphouston** [comment]
Working great! Was crashing again before the update and now it's working.
