### ISSUE TITLE
[FEATURE_REQUEST] 

### ISSUE THREAD

**Issue by kanado01** [mateusz-bak/openreads-android#86]
This app is missing two key features that make it a viable alternative to goodreads. First, the app should have an option to import csv book lists. The main export option on goodreads and another app called badreads is csv backups. In order to migrate from either csv file importation is necessary. Second, it would be nice to have a yearly reading goal progress screen. This is another feature goodreads and badreads have. With these two features openreads would be the best reading tracker app available.

**Comment by pionaiki** [comment]
CSV import related issue: #57, seems like the maintainer will work on this soon ;)

**Comment by mateusz-bak** [comment]
Hi @jakubnewcomb yeah as @pionaiki said I'm currently working on a CSV import/export. And for the yearly progress you can check that in statistics screen (for 2022 tab you have the option to see books progress and pages progress). Let me know if you have any questions or suggestions about this.

**Comment by mateusz-bak** [comment]
Implemneted, will be released in v1.15.0
