### ISSUE TITLE
[FEATURE_REQUEST] Add additional `Date started` and `Date finished` fields for those who re-read.

### ISSUE THREAD

**Issue by pionaiki** [mateusz-bak/openreads-android#87]
I sometimes re-read books and I find no option to note that in the app.

I suggest a `+` button under the existing date fields that creates a new pair of fields with a trash bin icon next to them. Like on the edited screenshots:
<p float="left">
  <img src="https://user-images.githubusercontent.com/51377752/170521303-2b68f896-7b5c-45db-82e8-c7dc5d8f4290.png" width="216px" />
  <img src="https://user-images.githubusercontent.com/51377752/170521313-bf137584-68ed-4743-a18c-8e56a66a9003.png" width="216px" />
</p>

Currently, I add the book twice and add a `Reread` tag, but anytime I want to change something I need to do it in 2+ places.

Additionally, information about the `re-read` stutus could appear in filters, statistics etc. The user could have a new option in the sorting settings to either list re-reads twice/more times in the book list view or display the book once with both dates listed. I also think that re-reading a book should increment the `Finished` counters in statistics, alternatively, it could appear as a new status (like `Not finished books`).

**Comment by mateusz-bak** [comment]
Hello @pionaiki I like the idea and your designs, will try to implement in the nearest future!

**Comment by McBaumwolle** [comment]
I really like (and miss) this idea! Is there any update on this maybe?

**Comment by mateusz-bak** [comment]
Not currently sorry. I'll add it to 2.4.0 milestone now and look at it at some time.

**Comment by mateusz-bak** [comment]
@pionaiki @McBaumwolle implemented in #436 

Will be released in 2.4.0 anytime now

**Comment by McBaumwolle** [comment]
omg thank you sm!
