### ISSUE TITLE
[FEATURE_REQUEST] Possibility to choose edition of work, togheter with its cover

### ISSUE THREAD

**Issue by ghost** [mateusz-bak/openreads-android#89]
Hello! I have a feature proposal that would fit nicely with [this one](https://github.com/mateusz-bak/openreads-android/issues/42).

Many books have different **editions**, all derivative of an original work; take [The professor ](https://openlibrary.org/works/OL271361W/The_professor?edition=ia%3Aprofessortaleofc01bronrich) by Charlotte Bronte, for example: 75 editions, with their own unique variations and covers.

It'd be nice if one could choose which edition they're reading, so that they can add the same work multiple times, with different editions; for example, a work could have multiple translation that differ a lot from each other, thus making it worth to read them all.

**Comment by mateusz-bak** [comment]
Thanks for the suggestion @felysu I need to rethink the whole process of getting books from Open Library as I had some workaround for displaying editions not in english language. Will keep this one in mind

**Comment by mateusz-bak** [comment]
This should be fixed in v2. You can choose editions of books when adding a new one.
