### ISSUE TITLE
[FEATURE_REQUEST] Don't count 0-star ratings in the average rating statistic or give an option to not leave a rating under a book.

### ISSUE THREAD

**Issue by pionaiki** [mateusz-bak/openreads-android#91]
There are books that I've read but don't want to rate (eg. setbooks, books I didn't like but think they are good etc.) and there is no option to not count them towards the average books rating in statistics.

I would like the app to either not count the 0-star ratings towards the average or give us an option on the book info editing page (maybe a crossed star to the left of the 5 stars or a checkbox to the left of the `Your rating` caption) to not give a rating.

**Comment by mateusz-bak** [comment]
Ok so after giving it some thought I agree - it makes sense to not count 0 starts to average rating. It should be treated as not rated

**Comment by mateusz-bak** [comment]
Fixed, will be released in v1.15.0
