### ISSUE TITLE
[FEATURE_REQUEST] Add more space to write in the "notes" section, change its name to "review"

### ISSUE THREAD

**Issue by Tototu76** [mateusz-bak/openreads-android#93]
Add more space to write in the "notes" section, since it is too little space, and maybe change its name to "review", because that function does more with that than being "notes" itself, which I personally really likes

Create a space at the end where you can write comfortably, and be able to lower and raise the text (which is very easy now, because it can only be done with the cursor)

**Comment by mateusz-bak** [comment]
Hey @Tototu76 the point make sense, thank you! Will try to implement.

**Comment by mateusz-bak** [comment]
@Tototu76 I changed the notes to review, and increased the size of the text box (it will resize when you add more lines).

But I struggle to understand this: 

> Create a space at the end where you can write comfortably, and be able to lower and raise the text (which is very easy now, because it can only be done with the cursor)

Would you explain more about this?

**Comment by Tototu76** [comment]
> 

First, thank you very much for taking into account the opinion of your user, your app and you are incredible! ^^

Now, sorry for my bad english, i meant that it would be nice if the "review" space was not next to the cover, but in its own place at the end of the editing space. And about the cursor: when you want to lower or raise the text you've been writing in the box, you find that you can't slide the screen and that's it, instead you have to use the cell phone's cursor to scroll, which is very complicated. It's a common thing that happens on mobile, but if it's something that could be changed, that would be good, but if not, that's fine too.

And once again, thank you for your attention to your users, lots of support for your great app!! ^^

**Comment by Tototu76** [comment]
> @Tototu76 I changed the notes to review, and increased the size of the text box (it will resize when you add more lines).
> 
> But I struggle to understand this:
> 
> > Create a space at the end where you can write comfortably, and be able to lower and raise the text (which is very easy now, because it can only be done with the cursor)
> 
> Would you explain more about this?

First, thank you very much for taking into account the opinion of your user, your app and you are incredible! ^^

Now, sorry for my bad english, i meant that it would be nice if the "review" space was not next to the cover, but in its own place at the end of the editing space. And about the cursor: when you want to lower or raise the text you've been writing in the box, you find that you can't slide the screen and that's it, instead you have to use the cell phone's cursor to scroll, which is very complicated. It's a common thing that happens on mobile, but if it's something that could be changed, that would be good, but if not, that's fine too.

And once again, thank you for your attention to your users, lots of support for your great app!! ^^

**Comment by mateusz-bak** [comment]
Hey @Tototu76 check if version [v1.16.0-rc1](https://github.com/mateusz-bak/openreads-android/releases/tag/v1.16.0-rc1) and see if that's what you have in mind and if there are any changes I should make ;)

**Comment by Tototu76** [comment]
Hiii @mateusz-bak 
It looks really great!! Only two things, the first is that there is still a very small writing limit, when on average the reviews (at least mine, and from readers I know) tend to be very long, and the second is that, for ease from the user, I think it would be better to put the cover box above and not below the editing space :o
That's all, thank you very much ^^

**Comment by mateusz-bak** [comment]
I missed the text limit, good catch. Will increase to something big.

And the covers do yoy think it should be at the top even above book title?

**Comment by mateusz-bak** [comment]
I changed to 2000 characters do you think that is enough? 

Also I think the cover will look best at the bottom anyway because it only takes half of the screen and I don't want to mess with the layout. Maybe when we have more fields in the future and I will need to redesign the page I will move it to top or somewhere else!

**Comment by Tototu76** [comment]
Your resolution with the matter of the cover seems good to me. And, with the 2000 characters, well, counting the characters of one of my last reviews, it reaches 4000, I don't know what you think of that, or if you can enlarge it :o

**Comment by mateusz-bak** [comment]
4000? Amazing! Let's make the max 5000 then?

**Comment by Tototu76** [comment]
That was a such great book, hahaha. Yeees, that would be incredible, thank you ^^

**Comment by mateusz-bak** [comment]
Cool! Implemented, will be released in v1.16.0 soon
