### ISSUE TITLE
[FEATURE_REQUEST] Fediverse bookwyrm Integration

### ISSUE THREAD

**Issue by thrillfall** [mateusz-bak/openreads-android#96]
https://joinbookwyrm.com/
is your library connected to the library of other through fediverse. You can track your readings, your want to read, have read, reading challenges. You can follow others in their reading.

It is like goodreads but without evilcorp owning and monetizing your data and behavior.

How could this look like?
Your activity in the app could be synced to your bookwyrm account. The app could show what your bookwyrm instance notifies you about.

**Comment by thrillfall** [comment]
Bookwyrm is not exposing an api yet (besides activityPub)

**Comment by ericsomto** [comment]
Impressive idea

**Comment by seniorm0ment** [comment]
I would be highly interested in this if/when possible

**Comment by mateusz-bak** [comment]
Would be something interesting but as mentioned before Bookwyrm unfortunately does not expose any public API.

If this changes let me know.

**Comment by Bout2GitIt** [comment]
I may have a temporary workaround:

BookWyrm supports exporting the user's reading list as a .CSV.

Is there any way to convert that CSV into a OpenRead .backup file, and then restore from that?

 It's not the easiest solution, but at least it will let me sync the two apps for now.

**Comment by mateusz-bak** [comment]
@Bout2GitIt Openreads will support csv import since 2.3 version. You can send me your csv from BookWyrm to the emal that's mentioned in Openreads setting so I can make sure it works.

**Comment by mateusz-bak** [comment]
With slight delay BookWyrm CSV import is implemented (in 2.4.0) version.

Although all the books are set as finished ones because there is no information about book's status in the CSV.

**Comment by pabloscloud** [comment]
That's not what was asked. It was asked for "synced" integration not just import, export. I respect your efforts and it's definitely a step in the right direction, but that's not the issue.

I also see why this isn't currently possible as there is no API yet, but that still doesn't solve the issue. I'd just leave it open :)

**Comment by mateusz-bak** [comment]
@pabloscloud I wanna be honest and don't want to keep anyone's hopes up as I really don't see myself implementing this in the nearest future. It's just a simple offline books tracker after all.

For syncing with BookWyrm I suggest you try an app specifically for it, for example: https://github.com/PrivacyDragon/Bookwyrm_Android
